// -------------------------------------------------------------
// 
// File Name: hdlsrc/adder/add_fp32.v
// Created: 2026-09-05 17:15:38
// 
// Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// Out1                          ce_out        1
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: add_fp32
// Source Path: adder/add_fp32
// Hierarchy Level: 0
// Model version: 1.3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module add_fp32
          (clk,
           reset,
           clk_enable,
           In1,
           In2,
           ce_out,
           Out1);


  input   clk;
  input   reset;
  input   clk_enable;
  input   [31:0] In1;  // single
  input   [31:0] In2;  // single
  output  ce_out;
  output  [31:0] Out1;  // single


  wire [31:0] Add_out1;  // ufix32


  nfp_add_single u_nfp_add_comp (.clk(clk),
                                 .reset(reset),
                                 .enb(clk_enable),
                                 .nfp_in1(In1),  // single
                                 .nfp_in2(In2),  // single
                                 .nfp_out(Add_out1)  // single
                                 );

  assign Out1 = Add_out1;

  assign ce_out = clk_enable;

endmodule  // add_fp32

