// -------------------------------------------------------------
// 
// File Name: hdlsrc/adder/add_fp32.v
// Created: 2026-09-06 15:42:53
// 
// Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: add_fp32
// Source Path: adder/CS_TT/add_fp32
// Hierarchy Level: 1
// Model version: 1.5
// 
// -------------------------------------------------------------
/* verilator lint_off TIMESCALEMOD */
/* verilator lint_off WIDTHEXPAND */
/* verilator lint_off UNUSEDSIGNAL */

module add_fp32
          (clk,
           reset,
           enb,
           In1,
           In2,
           Out1);


  input   clk;
  input   reset;
  input   enb;
  input   [31:0] In1;  // single
  input   [31:0] In2;  // single
  output  [31:0] Out1;  // single


  wire [31:0] Add_out1;  // ufix32


  nfp_add_single u_nfp_add_comp (.clk(clk),
                                 .reset(reset),
                                 .enb(enb),
                                 .nfp_in1(In1),  // single
                                 .nfp_in2(In2),  // single
                                 .nfp_out(Add_out1)  // single
                                 );

  assign Out1 = Add_out1;

endmodule  // add_fp32

