// -------------------------------------------------------------
// 
// File Name: hdlsrc/adder/CS_TT.v
// Created: 2026-09-06 15:42:53
// 
// Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// Out1                          ce_out        1
// count                         ce_out        1
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: CS_TT
// Source Path: adder/CS_TT
// Hierarchy Level: 0
// Model version: 1.5
// 
// -------------------------------------------------------------
/* verilator lint_off TIMESCALEMOD */
/* verilator lint_off WIDTHEXPAND */
/* verilator lint_off UNUSEDSIGNAL */

module CS_TT
          (clk,
           reset,
           clk_enable,
           In1,
           In2,
           rst,
           dir,
           ce_out,
           Out1,
           count);


  input   clk;
  input   reset;
  input   clk_enable;
  input   [31:0] In1;  // single
  input   [31:0] In2;  // single
  input   rst;
  input   dir;
  output  ce_out;
  output  [31:0] Out1;  // single
  output  [7:0] count;  // uint8


  wire enb;
  wire [31:0] add_fp32_Out1;  // ufix32
  wire [7:0] count_step;  // uint8
  wire [7:0] count_from;  // uint8
  wire [7:0] count_reset;  // uint8
  reg [7:0] HDL_Counter_out1;  // uint8
  wire [7:0] count_1;  // uint8
  wire need_to_wrap;
  wire [7:0] count_value;  // uint8
  wire [7:0] count_2;  // uint8
  wire [7:0] count_3;  // uint8
  reg [7:0] delayMatch_reg [0:5];  // ufix8 [6]
  reg [7:0] delayMatch_reg_next [0:5];  // ufix8 [6]
  reg [7:0] HDL_Counter_out1_1;  // uint8
  reg signed [31:0] delayMatch_t_0_0;  // int32
  reg signed [31:0] delayMatch_t_0_1;  // int32
  reg signed [31:0] delayMatch_t_1;  // int32


  add_fp32 u_add_fp32 (.clk(clk),
                       .reset(reset),
                       .enb(clk_enable),
                       .In1(In1),  // single
                       .In2(In2),  // single
                       .Out1(add_fp32_Out1)  // single
                       );

  assign Out1 = add_fp32_Out1;

  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 25
  assign count_step = 8'b00000001;

  assign count_from = 8'b00000000;

  assign count_reset = 8'b00000000;

  assign enb = clk_enable;

  assign count_1 = HDL_Counter_out1 + count_step;

  assign need_to_wrap = HDL_Counter_out1 == 8'b00011001;

  assign count_value = (need_to_wrap == 1'b0 ? count_1 :
              count_from);

  assign count_2 = (dir == 1'b0 ? HDL_Counter_out1 :
              count_value);

  assign count_3 = (rst == 1'b0 ? count_2 :
              count_reset);

  always @(posedge clk or posedge reset)
    begin : HDL_Counter_process
      if (reset == 1'b1) begin
        HDL_Counter_out1 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          HDL_Counter_out1 <= count_3;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        for(delayMatch_t_1 = 32'sd0; delayMatch_t_1 <= 32'sd5; delayMatch_t_1 = delayMatch_t_1 + 32'sd1) begin
          delayMatch_reg[delayMatch_t_1] <= 8'b00000000;
        end
      end
      else begin
        if (enb) begin
          for(delayMatch_t_0_1 = 32'sd0; delayMatch_t_0_1 <= 32'sd5; delayMatch_t_0_1 = delayMatch_t_0_1 + 32'sd1) begin
            delayMatch_reg[delayMatch_t_0_1] <= delayMatch_reg_next[delayMatch_t_0_1];
          end
        end
      end
    end

  always @* begin
    HDL_Counter_out1_1 = delayMatch_reg[5];
    delayMatch_reg_next[0] = HDL_Counter_out1;

    for(delayMatch_t_0_0 = 32'sd0; delayMatch_t_0_0 <= 32'sd4; delayMatch_t_0_0 = delayMatch_t_0_0 + 32'sd1) begin
      delayMatch_reg_next[delayMatch_t_0_0 + 32'sd1] = delayMatch_reg[delayMatch_t_0_0];
    end

  end

  assign count = HDL_Counter_out1_1;

  assign ce_out = clk_enable;

endmodule  // CS_TT

