// -------------------------------------------------------------
// 
// File Name: hdlsrc/MAC/FP16.v
// Created: 2026-09-05 16:36:26
// 
// Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FP16
// Source Path: MAC/FP16
// Hierarchy Level: 0
// Model version: 1.4
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module FP16
          (a,
           b,
           c,
           Out);


  input   signed [7:0] a;  // int8
  input   signed [7:0] b;  // int8
  input   signed [7:0] c;  // int8
  output  signed [15:0] Out;  // int16


  wire signed [15:0] mulOutput;  // sfix16
  wire signed [31:0] Multiply_Add_add_add_temp;  // sfix32
  wire signed [31:0] Multiply_Add_add_1;  // sfix32
  wire signed [31:0] Multiply_Add_add_2;  // sfix32
  wire signed [15:0] Multiply_Add_out1;  // int16


  assign mulOutput = a * b;

  assign Multiply_Add_add_1 = {{24{c[7]}}, c};
  assign Multiply_Add_add_2 = {{16{mulOutput[15]}}, mulOutput};
  assign Multiply_Add_add_add_temp = Multiply_Add_add_1 + Multiply_Add_add_2;
  assign Multiply_Add_out1 = Multiply_Add_add_add_temp[15:0];

  assign Out = Multiply_Add_out1;

endmodule  // FP16

