// -------------------------------------------------------------
// 
// File Name: hdlsrc/MAC/FP16.v
// Created: 2026-09-05 13:50:56
// 
// Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// Out                           ce_out        1
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FP16
// Source Path: MAC/FP16
// Hierarchy Level: 0
// Model version: 1.3
// 
// -------------------------------------------------------------

module FP16
          (clk,
           reset,
           clk_enable,
           a,
           b,
           c,
           ce_out,
           Out);


  input   clk;
  input   reset;
  input   clk_enable;
  input   [31:0] a;  // single
  input   [31:0] b;  // single
  input   [31:0] c;  // single
  output  ce_out;
  output  [31:0] Out;  // single


  wire enb;
  reg [31:0] delayMatch_reg [0:5];  // ufix32 [6]
  reg [31:0] delayMatch_reg_next [0:5];  // ufix32 [6]
  reg [31:0] c_1;  // ufix32
  wire [31:0] mul_out;  // ufix32
  wire [31:0] Multiply_Add_out1;  // ufix32
  reg signed [31:0] delayMatch_t_0_0;  // int32
  reg signed [31:0] delayMatch_t_0_1;  // int32
  reg signed [31:0] delayMatch_t_1;  // int32


  assign enb = clk_enable;

  always @(posedge clk or posedge reset)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        for(delayMatch_t_1 = 32'sd0; delayMatch_t_1 <= 32'sd5; delayMatch_t_1 = delayMatch_t_1 + 32'sd1) begin
          delayMatch_reg[delayMatch_t_1] <= 32'h00000000;
        end
      end
      else begin
        if (enb) begin
          for(delayMatch_t_0_1 = 32'sd0; delayMatch_t_0_1 <= 32'sd5; delayMatch_t_0_1 = delayMatch_t_0_1 + 32'sd1) begin
            delayMatch_reg[delayMatch_t_0_1] <= delayMatch_reg_next[delayMatch_t_0_1];
          end
        end
      end
    end

  always @* begin
    c_1 = delayMatch_reg[5];
    delayMatch_reg_next[0] = c;

    for(delayMatch_t_0_0 = 32'sd0; delayMatch_t_0_0 <= 32'sd4; delayMatch_t_0_0 = delayMatch_t_0_0 + 32'sd1) begin
      delayMatch_reg_next[delayMatch_t_0_0 + 32'sd1] = delayMatch_reg[delayMatch_t_0_0];
    end

  end

  nfp_mul_single u_nfp_mul_comp (.clk(clk),
                                 .reset(reset),
                                 .enb(clk_enable),
                                 .nfp_in1(a),  // single
                                 .nfp_in2(b),  // single
                                 .nfp_out(mul_out)  // single
                                 );

  nfp_add_single u_nfp_add_comp (.clk(clk),
                                 .reset(reset),
                                 .enb(clk_enable),
                                 .nfp_in1(c_1),  // single
                                 .nfp_in2(mul_out),  // single
                                 .nfp_out(Multiply_Add_out1)  // single
                                 );

  assign Out = Multiply_Add_out1;

  assign ce_out = clk_enable;

endmodule  // FP16

