// -------------------------------------------------------------
// 
// File Name: hdlsrc/MAC/nfp_add_single.v
// Created: 2026-09-05 13:50:56
// 
// Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: nfp_add_single
// Source Path: MAC/FP16/nfp_add_single
// Hierarchy Level: 1
// Model version: 1.3
// 
// {Latency Strategy = "Min"}
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module nfp_add_single
          (clk,
           reset,
           enb,
           nfp_in1,
           nfp_in2,
           nfp_out);


  input   clk;
  input   reset;
  input   enb;
  input   [31:0] nfp_in1;  // ufix32
  input   [31:0] nfp_in2;  // ufix32
  output  [31:0] nfp_out;  // ufix32


  wire AS;  // ufix1
  wire [7:0] AE;  // ufix8
  wire [22:0] AM;  // ufix23
  reg [7:0] Delay1_out1;  // ufix8
  wire BS;  // ufix1
  wire [7:0] BE;  // ufix8
  wire [22:0] BM;  // ufix23
  reg [7:0] Delay4_out1;  // ufix8
  wire Relational_Operator1_out1;  // ufix1
  reg [22:0] Delay2_out1;  // ufix23
  reg [22:0] Delay5_out1;  // ufix23
  wire Relational_Operator_out1;  // ufix1
  wire bitconcat_aExponent_aMantissa_out1;  // ufix1
  wire Logical_Operator_out1;  // ufix1
  wire Logical_Operator1_out1;  // ufix1
  wire [7:0] if_bitconcat_aExponent_aMantiss_out1;  // ufix8
  wire aExponent_cfType_Exponent_I_out1;  // ufix1
  reg  Delay11_out1;  // ufix1
  reg  Delay42_out1;  // ufix1
  reg  [1:0] Delay18_reg;  // ufix1 [2]
  wire Delay18_out1;  // ufix1
  wire Exponent_0_out1;  // ufix1
  wire [7:0] C_out1;  // ufix8
  wire [7:0] if_Exponent_0_out1;  // ufix8
  reg [7:0] Delay_out1;  // ufix8
  reg [7:0] Delay4_out1_1;  // ufix8
  reg [7:0] Delay2_out1_1;  // ufix8
  wire exp_norm_cfType_Exponent_In_out1;  // ufix1
  wire alpha_Exponent_0_cfType_Exp_out1;  // ufix1
  wire [2:0] alpha1_out1;  // ufix3
  wire [2:0] alpha0_out1;  // ufix3
  wire [2:0] if_Exponent_0_cfType_Exp_out1;  // ufix3
  wire [22:0] if_bitconcat_aExponent_aMantiss_1_out1;  // ufix23
  wire [25:0] Bit_Concat_out1;  // ufix26
  wire [1:0] alpha0_1_out1;  // ufix2
  wire [27:0] Bit_Concat1_out1;  // ufix28
  wire signed [27:0] Data_Type_Conversion_out1;  // sfix28
  reg signed [27:0] Delay2_out1_2;  // sfix28
  reg signed [27:0] Delay5_out1_1;  // sfix28
  reg  Delay3_out1;  // ufix1
  reg  Delay_out1_1;  // ufix1
  wire if_bitconcat_aExponent_aMantiss_2_out1;  // ufix1
  wire if_bitconcat_aExponent_aMantiss_5_out1;  // ufix1
  wire bitxor_out1;  // ufix1
  reg  Delay10_out1;  // ufix1
  wire [7:0] if_bitconcat_aExponent_aMantiss_3_out1;  // ufix8
  wire exp_b_cfType_Exponent_Inf_o_out1;  // ufix1
  wire Exponent_0_out1_1;  // ufix1
  wire alpha_Exponent_0_cfType_Exp_out1_1;  // ufix1
  wire [2:0] alpha1_out1_1;  // ufix3
  wire [2:0] alpha0_out1_1;  // ufix3
  wire [2:0] if_Exponent_0_cfType_Exp_out1_1;  // ufix3
  wire [22:0] if_bitconcat_aExponent_aMantiss_4_out1;  // ufix23
  wire [25:0] Bit_Concat_out1_1;  // ufix26
  wire [1:0] alpha0_1_out1_1;  // ufix2
  wire [27:0] Bit_Concat1_out1_1;  // ufix28
  wire signed [27:0] Data_Type_Conversion_out1_1;  // sfix28
  reg signed [27:0] Delay1_out1_1;  // sfix28
  wire signed [28:0] alpha_mant_b_ext_in0;  // sfix29
  wire signed [28:0] alpha_mant_b_ext_1;  // sfix29
  wire signed [27:0] alpha_mant_b_ext_out1;  // sfix28
  wire signed [27:0] if_opp_Sign_out1;  // sfix28
  wire [7:0] C_out1_1;  // ufix8
  wire [7:0] if_Exponent_0_out1_1;  // ufix8
  reg [7:0] Delay_out1_2;  // ufix8
  wire signed [31:0] storedInteger_exp_a_cor_sto_1;  // sfix32
  wire signed [31:0] storedInteger_exp_a_cor_sto_2;  // sfix32
  wire signed [31:0] storedInteger_exp_a_cor_sto_out1;  // int32
  wire [2:0] Bit_Slice2_out1;  // ufix3
  wire Compare_To_Zero_out1;  // ufix1
  wire [4:0] Constant_out1;  // ufix5
  wire [4:0] Bit_Slice_out1;  // ufix5
  wire [4:0] if_opp_Sign_1_out1;  // ufix5
  wire [7:0] dynamic_shift_1;  // uint8
  wire signed [27:0] bitsra_mant_b_ext_shift_lengt_out1;  // sfix28
  reg signed [27:0] Delay1_out1_2;  // sfix28
  wire signed [31:0] mant_a_ext_mant_b_shifted_add_temp;  // sfix32
  wire signed [31:0] mant_a_ext_mant_b_shifted_1;  // sfix32
  wire signed [31:0] mant_a_ext_mant_b_shifted_2;  // sfix32
  wire [26:0] mant_a_ext_mant_b_shifted_out1;  // ufix27
  wire BitSlice_out1;  // ufix1
  reg  Delay3_out1_1;  // ufix1
  wire Logical_Operator_out1_1;  // ufix1
  reg  Delay13_out1;  // ufix1
  reg [26:0] Delay1_out1_3;  // ufix27
  wire [25:0] BitSlice3_out1;  // ufix26
  wire Bit_Slice5_out1;  // ufix1
  wire Bit_Slice3_out1;  // ufix1
  wire Logical_Operator1_out1_1;  // ufix1
  wire [7:0] Bit_Slice2_out1_1;  // ufix8
  wire Bit_Slice16_out1;  // ufix1
  wire Bit_Slice15_out1;  // ufix1
  wire Logical_Operator5_out1;  // ufix1
  wire Bit_Slice14_out1;  // ufix1
  wire Bit_Slice13_out1;  // ufix1
  wire Logical_Operator7_out1;  // ufix1
  wire Logical_Operator6_out1;  // ufix1
  wire Bit_Slice12_out1;  // ufix1
  wire Bit_Slice11_out1;  // ufix1
  wire Logical_Operator4_out1;  // ufix1
  wire Bit_Slice10_out1;  // ufix1
  wire Bit_Slice9_out1;  // ufix1
  wire Logical_Operator14_out1;  // ufix1
  wire Logical_Operator13_out1;  // ufix1
  wire Logical_Operator12_out1;  // ufix1
  wire [7:0] Bit_Slice1_out1;  // ufix8
  wire Bit_Slice16_out1_1;  // ufix1
  wire Bit_Slice15_out1_1;  // ufix1
  wire Logical_Operator5_out1_1;  // ufix1
  wire Bit_Slice14_out1_1;  // ufix1
  wire Bit_Slice13_out1_1;  // ufix1
  wire Logical_Operator7_out1_1;  // ufix1
  wire Logical_Operator6_out1_1;  // ufix1
  wire Bit_Slice12_out1_1;  // ufix1
  wire Bit_Slice11_out1_1;  // ufix1
  wire Logical_Operator4_out1_1;  // ufix1
  wire Bit_Slice10_out1_1;  // ufix1
  wire Bit_Slice9_out1_1;  // ufix1
  wire Logical_Operator14_out1_1;  // ufix1
  wire Logical_Operator13_out1_1;  // ufix1
  wire [7:0] Bit_Slice4_out1;  // ufix8
  wire Bit_Slice8_out1;  // ufix1
  wire Bit_Slice7_out1;  // ufix1
  wire Logical_Operator1_out1_2;  // ufix1
  wire Bit_Slice6_out1;  // ufix1
  wire Bit_Slice5_out1_1;  // ufix1
  wire Logical_Operator3_out1;  // ufix1
  wire Bit_Slice3_out1_1;  // ufix1
  wire Bit_Slice2_out1_2;  // ufix1
  wire Bit_Slice1_out1_1;  // ufix1
  wire Bit_Slice_out1_1;  // ufix1
  wire [4:0] Constant_out1_1;  // ufix5
  wire [4:0] Constant1_out1;  // ufix5
  wire [4:0] Switch_out1;  // ufix5
  wire Logical_Operator_out1_2;  // ufix1
  wire [4:0] Constant2_out1;  // ufix5
  wire [4:0] Switch1_out1;  // ufix5
  wire [4:0] Constant3_out1;  // ufix5
  wire [4:0] Switch2_out1;  // ufix5
  wire [4:0] Constant4_out1;  // ufix5
  wire Logical_Operator2_out1;  // ufix1
  wire [4:0] Switch3_out1;  // ufix5
  wire [4:0] Switch4_out1;  // ufix5
  wire [4:0] Constant5_out1;  // ufix5
  wire [4:0] Switch5_out1;  // ufix5
  wire [4:0] Constant6_out1;  // ufix5
  wire [4:0] Switch6_out1;  // ufix5
  wire [4:0] Constant7_out1;  // ufix5
  wire [4:0] Switch7_out1;  // ufix5
  wire [4:0] Constant8_out1;  // ufix5
  wire [4:0] Switch8_out1;  // ufix5
  wire Logical_Operator12_out1_1;  // ufix1
  wire [4:0] Switch9_out1;  // ufix5
  wire [4:0] Switch10_out1;  // ufix5
  wire [4:0] Constant9_out1;  // ufix5
  wire [4:0] Switch11_out1;  // ufix5
  wire [4:0] Constant10_out1;  // ufix5
  wire [4:0] Switch12_out1;  // ufix5
  wire [4:0] Constant11_out1;  // ufix5
  wire [4:0] Switch14_out1;  // ufix5
  wire [4:0] Constant12_out1;  // ufix5
  wire [4:0] Switch15_out1;  // ufix5
  wire [4:0] Switch16_out1;  // ufix5
  wire [4:0] Constant13_out1;  // ufix5
  wire [4:0] Switch17_out1;  // ufix5
  wire [4:0] Constant14_out1;  // ufix5
  wire [4:0] Switch18_out1;  // ufix5
  wire [4:0] Constant15_out1;  // ufix5
  wire [4:0] Switch19_out1;  // ufix5
  wire [4:0] Constant16_out1;  // ufix5
  wire [4:0] Switch20_out1;  // ufix5
  wire [4:0] Switch21_out1;  // ufix5
  wire Logical_Operator_out1_3;  // ufix1
  wire [4:0] Switch13_out1;  // ufix5
  wire [4:0] Switch33_out1;  // ufix5
  wire [4:0] Constant9_out1_1;  // ufix5
  wire [4:0] Switch11_out1_1;  // ufix5
  wire [4:0] Constant10_out1_1;  // ufix5
  wire [4:0] Switch12_out1_1;  // ufix5
  wire [4:0] Constant11_out1_1;  // ufix5
  wire [4:0] Switch14_out1_1;  // ufix5
  wire [4:0] Constant12_out1_1;  // ufix5
  wire [4:0] Switch15_out1_1;  // ufix5
  wire [4:0] Switch16_out1_1;  // ufix5
  wire [4:0] Constant13_out1_1;  // ufix5
  wire [4:0] Switch17_out1_1;  // ufix5
  wire [4:0] Constant14_out1_1;  // ufix5
  wire [4:0] Switch18_out1_1;  // ufix5
  wire [4:0] Constant15_out1_1;  // ufix5
  wire [4:0] Switch19_out1_1;  // ufix5
  wire [4:0] Constant16_out1_1;  // ufix5
  wire [4:0] Switch20_out1_1;  // ufix5
  wire [4:0] Switch21_out1_1;  // ufix5
  wire [4:0] Switch13_out1_1;  // ufix5
  wire [4:0] Constant1_out1_1;  // ufix5
  wire [4:0] Switch3_out1_1;  // ufix5
  wire [4:0] Constant2_out1_1;  // ufix5
  wire [4:0] Switch2_out1_1;  // ufix5
  wire [4:0] Switch1_out1_1;  // ufix5
  wire [4:0] Switch34_out1;  // ufix5
  reg [4:0] Delay_out1_3;  // ufix5
  wire [4:0] Bit_Slice_out1_2;  // ufix5
  wire shift_length_exp_a_cor_out1;  // ufix1
  wire [2:0] Bit_Slice1_out1_2;  // ufix3
  wire Compare_To_Zero_out1_1;  // ufix1
  wire Logical_Operator1_out1_3;  // ufix1
  wire [7:0] C1_out1;  // ufix8
  wire [4:0] exp_a_cor_1_sub_cast;  // ufix5
  wire [4:0] exp_a_cor_1_out1;  // ufix5
  wire [4:0] if_shift_length_exp_a_cor_1_out1;  // ufix5
  wire [7:0] dynamic_shift_3;  // uint8
  wire [26:0] bitsll_Sum_shift_length_out1;  // ufix27
  wire [26:0] bitsrl_Sum_1_out1;  // ufix27
  wire [26:0] if_bitget_Sum_Sum_WordLength_out1;  // ufix27
  reg [26:0] Delay15_out1;  // ufix27
  wire [26:0] C5_out1;  // ufix27
  wire [26:0] if_exp_norm_cfType_Exponent_I_out1;  // ufix27
  wire [23:0] BitSlice6_out1;  // ufix24
  wire BitSlice5_out1;  // ufix1
  wire Bit_Slice13_out1_2;  // ufix1
  wire Bit_Slice12_out1_2;  // ufix1
  wire Bit_Slice10_out1_2;  // ufix1
  wire Bit_Slice11_out1_2;  // ufix1
  wire Bit_Slice14_out1_2;  // ufix1
  wire [2:0] Bit_Slice7_out1_1;  // ufix3
  wire Constant1_out1_2;  // ufix1
  wire [3:0] Bit_Concat_out1_2;  // ufix4
  wire Bit_Slice_out1_3;  // ufix1
  wire Bit_Slice1_out1_3;  // ufix1
  wire Logical_Operator_out1_4;  // ufix1
  wire Switch6_out1_1;  // ufix1
  wire Bit_Slice2_out1_3;  // ufix1
  wire Logical_Operator1_out1_4;  // ufix1
  wire Bit_Slice3_out1_2;  // ufix1
  wire Logical_Operator2_out1_1;  // ufix1
  wire Switch7_out1_1;  // ufix1
  wire Switch3_out1_2;  // ufix1
  wire [3:0] Bit_Slice8_out1_1;  // ufix4
  wire Bit_Slice_out1_4;  // ufix1
  wire Logical_Operator3_out1_1;  // ufix1
  wire Bit_Slice1_out1_4;  // ufix1
  wire Logical_Operator_out1_5;  // ufix1
  wire Switch6_out1_2;  // ufix1
  wire Bit_Slice2_out1_4;  // ufix1
  wire Logical_Operator1_out1_5;  // ufix1
  wire Bit_Slice3_out1_3;  // ufix1
  wire Logical_Operator2_out1_2;  // ufix1
  wire Switch7_out1_2;  // ufix1
  wire Switch3_out1_3;  // ufix1
  wire Switch6_out1_3;  // ufix1
  wire [3:0] Bit_Slice9_out1_2;  // ufix4
  wire Bit_Slice_out1_5;  // ufix1
  wire Logical_Operator3_out1_2;  // ufix1
  wire Bit_Slice1_out1_5;  // ufix1
  wire Logical_Operator_out1_6;  // ufix1
  wire Switch6_out1_4;  // ufix1
  wire Bit_Slice2_out1_5;  // ufix1
  wire Logical_Operator1_out1_6;  // ufix1
  wire Bit_Slice3_out1_4;  // ufix1
  wire Logical_Operator2_out1_3;  // ufix1
  wire Switch7_out1_3;  // ufix1
  wire Switch3_out1_4;  // ufix1
  wire [3:0] Bit_Slice3_out1_5;  // ufix4
  wire Bit_Slice_out1_6;  // ufix1
  wire Logical_Operator3_out1_3;  // ufix1
  wire Bit_Slice1_out1_6;  // ufix1
  wire Logical_Operator_out1_7;  // ufix1
  wire Switch6_out1_5;  // ufix1
  wire Bit_Slice2_out1_6;  // ufix1
  wire Logical_Operator1_out1_7;  // ufix1
  wire Bit_Slice3_out1_6;  // ufix1
  wire Logical_Operator2_out1_4;  // ufix1
  wire Switch7_out1_4;  // ufix1
  wire Switch3_out1_5;  // ufix1
  wire Switch7_out1_5;  // ufix1
  wire Switch3_out1_6;  // ufix1
  wire [3:0] Bit_Slice4_out1_1;  // ufix4
  wire Bit_Slice_out1_7;  // ufix1
  wire Logical_Operator3_out1_4;  // ufix1
  wire Bit_Slice1_out1_7;  // ufix1
  wire Logical_Operator_out1_8;  // ufix1
  wire Switch6_out1_6;  // ufix1
  wire Bit_Slice2_out1_7;  // ufix1
  wire Logical_Operator1_out1_8;  // ufix1
  wire Bit_Slice3_out1_7;  // ufix1
  wire Logical_Operator2_out1_5;  // ufix1
  wire Switch7_out1_6;  // ufix1
  wire Switch3_out1_7;  // ufix1
  wire [3:0] Bit_Slice5_out1_2;  // ufix4
  wire Bit_Slice_out1_8;  // ufix1
  wire Logical_Operator3_out1_5;  // ufix1
  wire Bit_Slice1_out1_8;  // ufix1
  wire Logical_Operator_out1_9;  // ufix1
  wire Switch6_out1_7;  // ufix1
  wire Bit_Slice2_out1_8;  // ufix1
  wire Logical_Operator1_out1_9;  // ufix1
  wire Bit_Slice3_out1_8;  // ufix1
  wire Logical_Operator2_out1_6;  // ufix1
  wire Switch7_out1_7;  // ufix1
  wire Switch3_out1_8;  // ufix1
  wire Switch6_out1_8;  // ufix1
  wire [3:0] Bit_Slice6_out1_1;  // ufix4
  wire Bit_Slice_out1_9;  // ufix1
  wire Logical_Operator3_out1_6;  // ufix1
  wire Bit_Slice1_out1_9;  // ufix1
  wire Logical_Operator_out1_10;  // ufix1
  wire Switch6_out1_9;  // ufix1
  wire Bit_Slice2_out1_9;  // ufix1
  wire Logical_Operator1_out1_10;  // ufix1
  wire Bit_Slice3_out1_9;  // ufix1
  wire Logical_Operator2_out1_7;  // ufix1
  wire Switch7_out1_8;  // ufix1
  wire Switch3_out1_9;  // ufix1
  wire Bit_Slice1_out1_10;  // ufix1
  wire Logical_Operator_out1_11;  // ufix1
  wire Logical_Operator1_out1_11;  // ufix1
  wire Switch7_out1_9;  // ufix1
  wire Switch3_out1_10;  // ufix1
  wire Switch2_out1_2;  // ufix1
  reg  Delay_out1_4;  // ufix1
  reg  Delay12_out1;  // ufix1
  wire BitSlice1_out1;  // ufix1
  wire sticky_bitget_Sum_1_out1;  // ufix1
  reg  Delay4_out1_2;  // ufix1
  wire if_bitget_Sum_Sum_WordLength_2_out1;  // ufix1
  wire BitSlice_out1_1;  // ufix1
  wire BitSlice1_out1_1;  // ufix1
  reg  Delay19_out1;  // ufix1
  wire sticky_bitget_Sum_1_out1_1;  // ufix1
  wire alpha_bitget_Mant_tmp_2_0_out1;  // ufix1
  wire alpha_bitget_Mant_tmp_1_0_out1;  // ufix1
  wire alpha0_out1_2;  // ufix1
  wire [22:0] BitSlice4_out1;  // ufix23
  wire [23:0] Bit_Concat_out1_3;  // ufix24
  wire [23:0] cast_2_like_Mant_tmp_out1;  // ufix24
  wire [23:0] Mant_tmp_cast_2_like_Man_out1;  // ufix24
  wire [23:0] if_bitget_Mant_tmp_1_0_out1;  // ufix24
  wire BitSlice2_out1;  // ufix1
  wire BitSlice4_out1_1;  // ufix1
  wire [7:0] C4_out1;  // ufix8
  wire Sum_0_out1;  // ufix1
  wire [7:0] exp_a_cor_shift_length_1;  // ufix8
  wire [7:0] exp_a_cor_shift_length_out1;  // ufix8
  wire [7:0] C2_out1;  // ufix8
  wire [7:0] if_shift_length_exp_a_cor_out1;  // ufix8
  wire BitSlice2_out1_1;  // ufix1
  wire [7:0] C3_out1;  // ufix8
  wire [7:0] if_Sum_0_out1;  // ufix8
  wire [7:0] if_bitget_Sum_Sum_WordLength_1_out1;  // ufix8
  wire [7:0] C_out1_2;  // ufix8
  wire [7:0] exp_a_cor_1_out1_1;  // ufix8
  wire [7:0] if_bitget_Sum_Sum_WordLength_1_out1_1;  // ufix8
  reg [7:0] Delay14_out1;  // ufix8
  wire [7:0] if_bitget_Sum_Sum_WordLength_out1_1;  // ufix8
  wire [7:0] cast_1_like_Exp_out1;  // ufix8
  wire [7:0] Exp_cast_1_like_Exp_out1;  // ufix8
  wire [7:0] if_bitget_Mant_tmp_Mant_tmp_Wor_out1;  // ufix8
  wire Exponent_0_out1_2;  // ufix1
  wire [22:0] BitSlice3_out1_1;  // ufix23
  wire Mantissa_0_out1;  // ufix1
  wire alpha_Exponent_0_Mantissa_out1;  // ufix1
  wire Constant_out1_2;  // ufix1
  wire Switch_out1_1;  // ufix1
  reg  Delay12_out1_1;  // ufix1
  reg  Delay29_out1;  // ufix1
  reg  [1:0] Delay14_reg;  // ufix1 [2]
  wire Delay14_out1_1;  // ufix1
  wire alpha_aSign_1_bSign_1_out1;  // ufix1
  reg  Delay9_out1;  // ufix1
  reg  Delay25_out1;  // ufix1
  reg  [1:0] Delay13_reg;  // ufix1 [2]
  wire Delay13_out1_1;  // ufix1
  wire if_Exponent_0_Mantissa_out1;  // ufix1
  reg  Delay6_out1;  // ufix1
  reg [7:0] Delay32_out1;  // ufix8
  reg [7:0] Delay34_out1;  // ufix8
  reg [7:0] Delay15_reg [0:1];  // ufix8 [2]
  wire [7:0] Delay15_reg_next [0:1];  // ufix8 [2]
  wire [7:0] Delay15_out1_1;  // ufix8
  wire [7:0] if_aExponent_cfType_Exponent_out1;  // ufix8
  reg [7:0] Delay7_out1;  // ufix8
  wire opp_signs_exp_b_cfType_out1;  // ufix1
  wire mant_a_0_out1;  // ufix1
  wire alpha_mant_a_0_opp_signs_out1;  // ufix1
  wire [22:0] BitSet_out1;  // ufix23
  wire [22:0] if_mant_a_0_opp_signs_out1;  // ufix23
  reg [22:0] Delay2_out1_3;  // ufix23
  reg [22:0] Delay38_out1;  // ufix23
  reg [22:0] Delay17_reg [0:1];  // ufix23 [2]
  wire [22:0] Delay17_reg_next [0:1];  // ufix23 [2]
  wire [22:0] Delay17_out1;  // ufix23
  wire [22:0] if_aExponent_cfType_Exponent_1_out1;  // ufix23
  reg [22:0] Delay8_out1;  // ufix23
  wire [31:0] nfp_out_pack;  // ufix32
  reg signed [31:0] Delay15_t_0_0;  // int32
  reg signed [31:0] Delay15_t_1;  // int32
  reg signed [31:0] Delay17_t_0_0;  // int32
  reg signed [31:0] Delay17_t_1;  // int32


  // Split 32 bit word into FP sign, exponent, mantissa
  assign AS = nfp_in1[31];
  assign AE = nfp_in1[30:23];
  assign AM = nfp_in1[22:0];

  always @(posedge clk or posedge reset)
    begin : Delay1_process
      if (reset == 1'b1) begin
        Delay1_out1 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          Delay1_out1 <= AE;
        end
      end
    end

  // Split 32 bit word into FP sign, exponent, mantissa
  assign BS = nfp_in2[31];
  assign BE = nfp_in2[30:23];
  assign BM = nfp_in2[22:0];

  always @(posedge clk or posedge reset)
    begin : Delay4_process
      if (reset == 1'b1) begin
        Delay4_out1 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          Delay4_out1 <= BE;
        end
      end
    end

  assign Relational_Operator1_out1 = Delay1_out1 == Delay4_out1;

  always @(posedge clk or posedge reset)
    begin : Delay2_process
      if (reset == 1'b1) begin
        Delay2_out1 <= 23'b00000000000000000000000;
      end
      else begin
        if (enb) begin
          Delay2_out1 <= AM;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay5_process
      if (reset == 1'b1) begin
        Delay5_out1 <= 23'b00000000000000000000000;
      end
      else begin
        if (enb) begin
          Delay5_out1 <= BM;
        end
      end
    end

  assign Relational_Operator_out1 = Delay1_out1 > Delay4_out1;

  assign bitconcat_aExponent_aMantissa_out1 = Delay2_out1 >= Delay5_out1;

  assign Logical_Operator_out1 = Relational_Operator1_out1 & bitconcat_aExponent_aMantissa_out1;

  assign Logical_Operator1_out1 = Relational_Operator_out1 | Logical_Operator_out1;

  assign if_bitconcat_aExponent_aMantiss_out1 = (Logical_Operator1_out1 == 1'b0 ? Delay4_out1 :
              Delay1_out1);

  assign aExponent_cfType_Exponent_I_out1 = if_bitconcat_aExponent_aMantiss_out1 == 8'b11111111;

  always @(posedge clk or posedge reset)
    begin : Delay11_process
      if (reset == 1'b1) begin
        Delay11_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay11_out1 <= aExponent_cfType_Exponent_I_out1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay42_process
      if (reset == 1'b1) begin
        Delay42_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay42_out1 <= Delay11_out1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay18_process
      if (reset == 1'b1) begin
        Delay18_reg <= {2{1'b0}};
      end
      else begin
        if (enb) begin
          Delay18_reg[0] <= Delay42_out1;
          Delay18_reg[1] <= Delay18_reg[0];
        end
      end
    end

  assign Delay18_out1 = Delay18_reg[1];

  assign Exponent_0_out1 = if_bitconcat_aExponent_aMantiss_out1 == 8'b00000000;

  assign C_out1 = 8'b00000001;

  assign if_Exponent_0_out1 = (Exponent_0_out1 == 1'b0 ? if_bitconcat_aExponent_aMantiss_out1 :
              C_out1);

  always @(posedge clk or posedge reset)
    begin : Delay_process
      if (reset == 1'b1) begin
        Delay_out1 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          Delay_out1 <= if_Exponent_0_out1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay4_1_process
      if (reset == 1'b1) begin
        Delay4_out1_1 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          Delay4_out1_1 <= Delay_out1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay2_1_process
      if (reset == 1'b1) begin
        Delay2_out1_1 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          Delay2_out1_1 <= Delay4_out1_1;
        end
      end
    end

  assign exp_norm_cfType_Exponent_In_out1 = Delay2_out1_1 == 8'b11111110;

  assign alpha_Exponent_0_cfType_Exp_out1 = aExponent_cfType_Exponent_I_out1 | Exponent_0_out1;

  assign alpha1_out1 = 3'b001;

  assign alpha0_out1 = 3'b000;

  assign if_Exponent_0_cfType_Exp_out1 = (alpha_Exponent_0_cfType_Exp_out1 == 1'b0 ? alpha1_out1 :
              alpha0_out1);

  assign if_bitconcat_aExponent_aMantiss_1_out1 = (Logical_Operator1_out1 == 1'b0 ? Delay5_out1 :
              Delay2_out1);

  assign Bit_Concat_out1 = {if_Exponent_0_cfType_Exp_out1, if_bitconcat_aExponent_aMantiss_1_out1};

  assign alpha0_1_out1 = 2'b00;

  assign Bit_Concat1_out1 = {Bit_Concat_out1, alpha0_1_out1};

  assign Data_Type_Conversion_out1 = Bit_Concat1_out1;

  always @(posedge clk or posedge reset)
    begin : Delay2_2_process
      if (reset == 1'b1) begin
        Delay2_out1_2 <= 28'sb0000000000000000000000000000;
      end
      else begin
        if (enb) begin
          Delay2_out1_2 <= Data_Type_Conversion_out1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay5_1_process
      if (reset == 1'b1) begin
        Delay5_out1_1 <= 28'sb0000000000000000000000000000;
      end
      else begin
        if (enb) begin
          Delay5_out1_1 <= Delay2_out1_2;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay3_process
      if (reset == 1'b1) begin
        Delay3_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay3_out1 <= BS;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay_1_process
      if (reset == 1'b1) begin
        Delay_out1_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay_out1_1 <= AS;
        end
      end
    end

  assign if_bitconcat_aExponent_aMantiss_2_out1 = (Logical_Operator1_out1 == 1'b0 ? Delay3_out1 :
              Delay_out1_1);

  assign if_bitconcat_aExponent_aMantiss_5_out1 = (Logical_Operator1_out1 == 1'b0 ? Delay_out1_1 :
              Delay3_out1);

  assign bitxor_out1 = if_bitconcat_aExponent_aMantiss_2_out1 ^ if_bitconcat_aExponent_aMantiss_5_out1;

  always @(posedge clk or posedge reset)
    begin : Delay10_process
      if (reset == 1'b1) begin
        Delay10_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay10_out1 <= bitxor_out1;
        end
      end
    end

  assign if_bitconcat_aExponent_aMantiss_3_out1 = (Logical_Operator1_out1 == 1'b0 ? Delay1_out1 :
              Delay4_out1);

  assign exp_b_cfType_Exponent_Inf_o_out1 = if_bitconcat_aExponent_aMantiss_3_out1 == 8'b11111111;

  assign Exponent_0_out1_1 = if_bitconcat_aExponent_aMantiss_3_out1 == 8'b00000000;

  assign alpha_Exponent_0_cfType_Exp_out1_1 = exp_b_cfType_Exponent_Inf_o_out1 | Exponent_0_out1_1;

  assign alpha1_out1_1 = 3'b001;

  assign alpha0_out1_1 = 3'b000;

  assign if_Exponent_0_cfType_Exp_out1_1 = (alpha_Exponent_0_cfType_Exp_out1_1 == 1'b0 ? alpha1_out1_1 :
              alpha0_out1_1);

  assign if_bitconcat_aExponent_aMantiss_4_out1 = (Logical_Operator1_out1 == 1'b0 ? Delay2_out1 :
              Delay5_out1);

  assign Bit_Concat_out1_1 = {if_Exponent_0_cfType_Exp_out1_1, if_bitconcat_aExponent_aMantiss_4_out1};

  assign alpha0_1_out1_1 = 2'b00;

  assign Bit_Concat1_out1_1 = {Bit_Concat_out1_1, alpha0_1_out1_1};

  assign Data_Type_Conversion_out1_1 = Bit_Concat1_out1_1;

  always @(posedge clk or posedge reset)
    begin : Delay1_1_process
      if (reset == 1'b1) begin
        Delay1_out1_1 <= 28'sb0000000000000000000000000000;
      end
      else begin
        if (enb) begin
          Delay1_out1_1 <= Data_Type_Conversion_out1_1;
        end
      end
    end

  assign alpha_mant_b_ext_1 = {Delay1_out1_1[27], Delay1_out1_1};
  assign alpha_mant_b_ext_in0 =  - (alpha_mant_b_ext_1);
  assign alpha_mant_b_ext_out1 = alpha_mant_b_ext_in0[27:0];

  assign if_opp_Sign_out1 = (Delay10_out1 == 1'b0 ? Delay1_out1_1 :
              alpha_mant_b_ext_out1);

  assign C_out1_1 = 8'b00000001;

  assign if_Exponent_0_out1_1 = (Exponent_0_out1_1 == 1'b0 ? if_bitconcat_aExponent_aMantiss_3_out1 :
              C_out1_1);

  always @(posedge clk or posedge reset)
    begin : Delay_2_process
      if (reset == 1'b1) begin
        Delay_out1_2 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          Delay_out1_2 <= if_Exponent_0_out1_1;
        end
      end
    end

  assign storedInteger_exp_a_cor_sto_1 = {24'b0, Delay_out1};
  assign storedInteger_exp_a_cor_sto_2 = {24'b0, Delay_out1_2};
  assign storedInteger_exp_a_cor_sto_out1 = storedInteger_exp_a_cor_sto_1 - storedInteger_exp_a_cor_sto_2;

  assign Bit_Slice2_out1 = storedInteger_exp_a_cor_sto_out1[7:5];

  assign Compare_To_Zero_out1 = Bit_Slice2_out1 == 3'b000;

  assign Constant_out1 = 5'b11111;

  assign Bit_Slice_out1 = storedInteger_exp_a_cor_sto_out1[4:0];

  assign if_opp_Sign_1_out1 = (Compare_To_Zero_out1 == 1'b0 ? Constant_out1 :
              Bit_Slice_out1);

  assign dynamic_shift_1 = {3'b0, if_opp_Sign_1_out1};
  assign bitsra_mant_b_ext_shift_lengt_out1 = if_opp_Sign_out1 >>> dynamic_shift_1;

  always @(posedge clk or posedge reset)
    begin : Delay1_2_process
      if (reset == 1'b1) begin
        Delay1_out1_2 <= 28'sb0000000000000000000000000000;
      end
      else begin
        if (enb) begin
          Delay1_out1_2 <= bitsra_mant_b_ext_shift_lengt_out1;
        end
      end
    end

  assign mant_a_ext_mant_b_shifted_1 = {{4{Delay5_out1_1[27]}}, Delay5_out1_1};
  assign mant_a_ext_mant_b_shifted_2 = {{4{Delay1_out1_2[27]}}, Delay1_out1_2};
  assign mant_a_ext_mant_b_shifted_add_temp = mant_a_ext_mant_b_shifted_1 + mant_a_ext_mant_b_shifted_2;
  assign mant_a_ext_mant_b_shifted_out1 = mant_a_ext_mant_b_shifted_add_temp[26:0];

  assign BitSlice_out1 = mant_a_ext_mant_b_shifted_out1[26];

  always @(posedge clk or posedge reset)
    begin : Delay3_1_process
      if (reset == 1'b1) begin
        Delay3_out1_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay3_out1_1 <= BitSlice_out1;
        end
      end
    end

  assign Logical_Operator_out1_1 = exp_norm_cfType_Exponent_In_out1 & Delay3_out1_1;

  always @(posedge clk or posedge reset)
    begin : Delay13_process
      if (reset == 1'b1) begin
        Delay13_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay13_out1 <= Logical_Operator_out1_1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay1_3_process
      if (reset == 1'b1) begin
        Delay1_out1_3 <= 27'b000000000000000000000000000;
      end
      else begin
        if (enb) begin
          Delay1_out1_3 <= mant_a_ext_mant_b_shifted_out1;
        end
      end
    end

  assign BitSlice3_out1 = mant_a_ext_mant_b_shifted_out1[25:0];

  assign Bit_Slice5_out1 = BitSlice3_out1[25];

  assign Bit_Slice3_out1 = BitSlice3_out1[24];

  assign Logical_Operator1_out1_1 = Bit_Slice5_out1 | Bit_Slice3_out1;

  assign Bit_Slice2_out1_1 = BitSlice3_out1[23:16];

  assign Bit_Slice16_out1 = Bit_Slice2_out1_1[7];

  assign Bit_Slice15_out1 = Bit_Slice2_out1_1[6];

  assign Logical_Operator5_out1 = Bit_Slice16_out1 | Bit_Slice15_out1;

  assign Bit_Slice14_out1 = Bit_Slice2_out1_1[5];

  assign Bit_Slice13_out1 = Bit_Slice2_out1_1[4];

  assign Logical_Operator7_out1 = Bit_Slice14_out1 | Bit_Slice13_out1;

  assign Logical_Operator6_out1 = Logical_Operator5_out1 | Logical_Operator7_out1;

  assign Bit_Slice12_out1 = Bit_Slice2_out1_1[3];

  assign Bit_Slice11_out1 = Bit_Slice2_out1_1[2];

  assign Logical_Operator4_out1 = Bit_Slice12_out1 | Bit_Slice11_out1;

  assign Bit_Slice10_out1 = Bit_Slice2_out1_1[1];

  assign Bit_Slice9_out1 = Bit_Slice2_out1_1[0];

  assign Logical_Operator14_out1 = Bit_Slice10_out1 | Bit_Slice9_out1;

  assign Logical_Operator13_out1 = Logical_Operator4_out1 | Logical_Operator14_out1;

  assign Logical_Operator12_out1 = Logical_Operator6_out1 | Logical_Operator13_out1;

  assign Bit_Slice1_out1 = BitSlice3_out1[15:8];

  assign Bit_Slice16_out1_1 = Bit_Slice1_out1[7];

  assign Bit_Slice15_out1_1 = Bit_Slice1_out1[6];

  assign Logical_Operator5_out1_1 = Bit_Slice16_out1_1 | Bit_Slice15_out1_1;

  assign Bit_Slice14_out1_1 = Bit_Slice1_out1[5];

  assign Bit_Slice13_out1_1 = Bit_Slice1_out1[4];

  assign Logical_Operator7_out1_1 = Bit_Slice14_out1_1 | Bit_Slice13_out1_1;

  assign Logical_Operator6_out1_1 = Logical_Operator5_out1_1 | Logical_Operator7_out1_1;

  assign Bit_Slice12_out1_1 = Bit_Slice1_out1[3];

  assign Bit_Slice11_out1_1 = Bit_Slice1_out1[2];

  assign Logical_Operator4_out1_1 = Bit_Slice12_out1_1 | Bit_Slice11_out1_1;

  assign Bit_Slice10_out1_1 = Bit_Slice1_out1[1];

  assign Bit_Slice9_out1_1 = Bit_Slice1_out1[0];

  assign Logical_Operator14_out1_1 = Bit_Slice10_out1_1 | Bit_Slice9_out1_1;

  assign Logical_Operator13_out1_1 = Logical_Operator4_out1_1 | Logical_Operator14_out1_1;

  assign Bit_Slice4_out1 = BitSlice3_out1[7:0];

  assign Bit_Slice8_out1 = Bit_Slice4_out1[7];

  assign Bit_Slice7_out1 = Bit_Slice4_out1[6];

  assign Logical_Operator1_out1_2 = Bit_Slice8_out1 | Bit_Slice7_out1;

  assign Bit_Slice6_out1 = Bit_Slice4_out1[5];

  assign Bit_Slice5_out1_1 = Bit_Slice4_out1[4];

  assign Logical_Operator3_out1 = Bit_Slice6_out1 | Bit_Slice5_out1_1;

  assign Bit_Slice3_out1_1 = Bit_Slice4_out1[3];

  assign Bit_Slice2_out1_2 = Bit_Slice4_out1[2];

  assign Bit_Slice1_out1_1 = Bit_Slice4_out1[1];

  assign Bit_Slice_out1_1 = Bit_Slice4_out1[0];

  assign Constant_out1_1 = 5'b11010;

  assign Constant1_out1 = 5'b11001;

  assign Switch_out1 = (Bit_Slice_out1_1 == 1'b0 ? Constant_out1_1 :
              Constant1_out1);

  assign Logical_Operator_out1_2 = Bit_Slice3_out1_1 | Bit_Slice2_out1_2;

  assign Constant2_out1 = 5'b11000;

  assign Switch1_out1 = (Bit_Slice1_out1_1 == 1'b0 ? Switch_out1 :
              Constant2_out1);

  assign Constant3_out1 = 5'b10111;

  assign Switch2_out1 = (Bit_Slice2_out1_2 == 1'b0 ? Constant_out1_1 :
              Constant3_out1);

  assign Constant4_out1 = 5'b10110;

  assign Logical_Operator2_out1 = Logical_Operator1_out1_2 | Logical_Operator3_out1;

  assign Switch3_out1 = (Bit_Slice3_out1_1 == 1'b0 ? Switch2_out1 :
              Constant4_out1);

  assign Switch4_out1 = (Logical_Operator_out1_2 == 1'b0 ? Switch1_out1 :
              Switch3_out1);

  assign Constant5_out1 = 5'b10101;

  assign Switch5_out1 = (Bit_Slice5_out1_1 == 1'b0 ? Constant_out1_1 :
              Constant5_out1);

  assign Constant6_out1 = 5'b10100;

  assign Switch6_out1 = (Bit_Slice6_out1 == 1'b0 ? Switch5_out1 :
              Constant6_out1);

  assign Constant7_out1 = 5'b10011;

  assign Switch7_out1 = (Bit_Slice7_out1 == 1'b0 ? Constant_out1_1 :
              Constant7_out1);

  assign Constant8_out1 = 5'b10010;

  assign Switch8_out1 = (Bit_Slice8_out1 == 1'b0 ? Switch7_out1 :
              Constant8_out1);

  assign Logical_Operator12_out1_1 = Logical_Operator6_out1_1 | Logical_Operator13_out1_1;

  assign Switch9_out1 = (Logical_Operator1_out1_2 == 1'b0 ? Switch6_out1 :
              Switch8_out1);

  assign Switch10_out1 = (Logical_Operator2_out1 == 1'b0 ? Switch4_out1 :
              Switch9_out1);

  assign Constant9_out1 = 5'b10001;

  assign Switch11_out1 = (Bit_Slice9_out1_1 == 1'b0 ? Constant_out1_1 :
              Constant9_out1);

  assign Constant10_out1 = 5'b10000;

  assign Switch12_out1 = (Bit_Slice10_out1_1 == 1'b0 ? Switch11_out1 :
              Constant10_out1);

  assign Constant11_out1 = 5'b01111;

  assign Switch14_out1 = (Bit_Slice11_out1_1 == 1'b0 ? Constant_out1_1 :
              Constant11_out1);

  assign Constant12_out1 = 5'b01110;

  assign Switch15_out1 = (Bit_Slice12_out1_1 == 1'b0 ? Switch14_out1 :
              Constant12_out1);

  assign Switch16_out1 = (Logical_Operator4_out1_1 == 1'b0 ? Switch12_out1 :
              Switch15_out1);

  assign Constant13_out1 = 5'b01101;

  assign Switch17_out1 = (Bit_Slice13_out1_1 == 1'b0 ? Constant_out1_1 :
              Constant13_out1);

  assign Constant14_out1 = 5'b01100;

  assign Switch18_out1 = (Bit_Slice14_out1_1 == 1'b0 ? Switch17_out1 :
              Constant14_out1);

  assign Constant15_out1 = 5'b01011;

  assign Switch19_out1 = (Bit_Slice15_out1_1 == 1'b0 ? Constant_out1_1 :
              Constant15_out1);

  assign Constant16_out1 = 5'b01010;

  assign Switch20_out1 = (Bit_Slice16_out1_1 == 1'b0 ? Switch19_out1 :
              Constant16_out1);

  assign Switch21_out1 = (Logical_Operator5_out1_1 == 1'b0 ? Switch18_out1 :
              Switch20_out1);

  assign Logical_Operator_out1_3 = Logical_Operator1_out1_1 | Logical_Operator12_out1;

  assign Switch13_out1 = (Logical_Operator6_out1_1 == 1'b0 ? Switch16_out1 :
              Switch21_out1);

  assign Switch33_out1 = (Logical_Operator12_out1_1 == 1'b0 ? Switch10_out1 :
              Switch13_out1);

  assign Constant9_out1_1 = 5'b01001;

  assign Switch11_out1_1 = (Bit_Slice9_out1 == 1'b0 ? Constant_out1_1 :
              Constant9_out1_1);

  assign Constant10_out1_1 = 5'b01000;

  assign Switch12_out1_1 = (Bit_Slice10_out1 == 1'b0 ? Switch11_out1_1 :
              Constant10_out1_1);

  assign Constant11_out1_1 = 5'b00111;

  assign Switch14_out1_1 = (Bit_Slice11_out1 == 1'b0 ? Constant_out1_1 :
              Constant11_out1_1);

  assign Constant12_out1_1 = 5'b00110;

  assign Switch15_out1_1 = (Bit_Slice12_out1 == 1'b0 ? Switch14_out1_1 :
              Constant12_out1_1);

  assign Switch16_out1_1 = (Logical_Operator4_out1 == 1'b0 ? Switch12_out1_1 :
              Switch15_out1_1);

  assign Constant13_out1_1 = 5'b00101;

  assign Switch17_out1_1 = (Bit_Slice13_out1 == 1'b0 ? Constant_out1_1 :
              Constant13_out1_1);

  assign Constant14_out1_1 = 5'b00100;

  assign Switch18_out1_1 = (Bit_Slice14_out1 == 1'b0 ? Switch17_out1_1 :
              Constant14_out1_1);

  assign Constant15_out1_1 = 5'b00011;

  assign Switch19_out1_1 = (Bit_Slice15_out1 == 1'b0 ? Constant_out1_1 :
              Constant15_out1_1);

  assign Constant16_out1_1 = 5'b00010;

  assign Switch20_out1_1 = (Bit_Slice16_out1 == 1'b0 ? Switch19_out1_1 :
              Constant16_out1_1);

  assign Switch21_out1_1 = (Logical_Operator5_out1 == 1'b0 ? Switch18_out1_1 :
              Switch20_out1_1);

  assign Switch13_out1_1 = (Logical_Operator6_out1 == 1'b0 ? Switch16_out1_1 :
              Switch21_out1_1);

  assign Constant1_out1_1 = 5'b00001;

  assign Switch3_out1_1 = (Bit_Slice3_out1 == 1'b0 ? Constant_out1_1 :
              Constant1_out1_1);

  assign Constant2_out1_1 = 5'b00000;

  assign Switch2_out1_1 = (Bit_Slice5_out1 == 1'b0 ? Switch3_out1_1 :
              Constant2_out1_1);

  assign Switch1_out1_1 = (Logical_Operator1_out1_1 == 1'b0 ? Switch13_out1_1 :
              Switch2_out1_1);

  assign Switch34_out1 = (Logical_Operator_out1_3 == 1'b0 ? Switch33_out1 :
              Switch1_out1_1);

  always @(posedge clk or posedge reset)
    begin : Delay_3_process
      if (reset == 1'b1) begin
        Delay_out1_3 <= 5'b00000;
      end
      else begin
        if (enb) begin
          Delay_out1_3 <= Switch34_out1;
        end
      end
    end

  assign Bit_Slice_out1_2 = Delay2_out1_1[4:0];

  assign shift_length_exp_a_cor_out1 = Delay_out1_3 >= Bit_Slice_out1_2;

  assign Bit_Slice1_out1_2 = Delay2_out1_1[7:5];

  assign Compare_To_Zero_out1_1 = Bit_Slice1_out1_2 == 3'b000;

  assign Logical_Operator1_out1_3 = shift_length_exp_a_cor_out1 & Compare_To_Zero_out1_1;

  assign C1_out1 = 8'b00000001;

  assign exp_a_cor_1_sub_cast = C1_out1[4:0];
  assign exp_a_cor_1_out1 = Bit_Slice_out1_2 - exp_a_cor_1_sub_cast;

  assign if_shift_length_exp_a_cor_1_out1 = (Logical_Operator1_out1_3 == 1'b0 ? Delay_out1_3 :
              exp_a_cor_1_out1);

  assign dynamic_shift_3 = {3'b0, if_shift_length_exp_a_cor_1_out1};
  assign bitsll_Sum_shift_length_out1 = Delay1_out1_3 <<< dynamic_shift_3;

  assign bitsrl_Sum_1_out1 = Delay1_out1_3 >> 8'd1;

  assign if_bitget_Sum_Sum_WordLength_out1 = (Delay3_out1_1 == 1'b0 ? bitsll_Sum_shift_length_out1 :
              bitsrl_Sum_1_out1);

  always @(posedge clk or posedge reset)
    begin : Delay15_process
      if (reset == 1'b1) begin
        Delay15_out1 <= 27'b000000000000000000000000000;
      end
      else begin
        if (enb) begin
          Delay15_out1 <= if_bitget_Sum_Sum_WordLength_out1;
        end
      end
    end

  assign C5_out1 = 27'b000000000000000000000000000;

  assign if_exp_norm_cfType_Exponent_I_out1 = (Delay13_out1 == 1'b0 ? Delay15_out1 :
              C5_out1);

  assign BitSlice6_out1 = if_exp_norm_cfType_Exponent_I_out1[24:1];

  assign BitSlice5_out1 = if_exp_norm_cfType_Exponent_I_out1[0];

  assign Bit_Slice13_out1_2 = if_opp_Sign_1_out1[4];

  assign Bit_Slice12_out1_2 = if_opp_Sign_1_out1[3];

  assign Bit_Slice10_out1_2 = if_opp_Sign_1_out1[2];

  assign Bit_Slice11_out1_2 = if_opp_Sign_1_out1[1];

  assign Bit_Slice14_out1_2 = if_opp_Sign_1_out1[0];

  assign Bit_Slice7_out1_1 = if_opp_Sign_out1[2:0];

  assign Constant1_out1_2 = 1'b0;

  assign Bit_Concat_out1_2 = {Bit_Slice7_out1_1, Constant1_out1_2};

  assign Bit_Slice_out1_3 = Bit_Concat_out1_2[0];

  assign Bit_Slice1_out1_3 = Bit_Concat_out1_2[1];

  assign Logical_Operator_out1_4 = Bit_Slice1_out1_3 | Bit_Slice_out1_3;

  assign Switch6_out1_1 = (Bit_Slice14_out1_2 == 1'b0 ? Bit_Slice_out1_3 :
              Logical_Operator_out1_4);

  assign Bit_Slice2_out1_3 = Bit_Concat_out1_2[2];

  assign Logical_Operator1_out1_4 = Bit_Slice2_out1_3 | Logical_Operator_out1_4;

  assign Bit_Slice3_out1_2 = Bit_Concat_out1_2[3];

  assign Logical_Operator2_out1_1 = Bit_Slice3_out1_2 | Logical_Operator1_out1_4;

  assign Switch7_out1_1 = (Bit_Slice14_out1_2 == 1'b0 ? Logical_Operator1_out1_4 :
              Logical_Operator2_out1_1);

  assign Switch3_out1_2 = (Bit_Slice11_out1_2 == 1'b0 ? Switch6_out1_1 :
              Switch7_out1_1);

  assign Bit_Slice8_out1_1 = if_opp_Sign_out1[6:3];

  assign Bit_Slice_out1_4 = Bit_Slice8_out1_1[0];

  assign Logical_Operator3_out1_1 = Bit_Slice_out1_4 | Logical_Operator2_out1_1;

  assign Bit_Slice1_out1_4 = Bit_Slice8_out1_1[1];

  assign Logical_Operator_out1_5 = Bit_Slice1_out1_4 | Logical_Operator3_out1_1;

  assign Switch6_out1_2 = (Bit_Slice14_out1_2 == 1'b0 ? Logical_Operator3_out1_1 :
              Logical_Operator_out1_5);

  assign Bit_Slice2_out1_4 = Bit_Slice8_out1_1[2];

  assign Logical_Operator1_out1_5 = Bit_Slice2_out1_4 | Logical_Operator_out1_5;

  assign Bit_Slice3_out1_3 = Bit_Slice8_out1_1[3];

  assign Logical_Operator2_out1_2 = Bit_Slice3_out1_3 | Logical_Operator1_out1_5;

  assign Switch7_out1_2 = (Bit_Slice14_out1_2 == 1'b0 ? Logical_Operator1_out1_5 :
              Logical_Operator2_out1_2);

  assign Switch3_out1_3 = (Bit_Slice11_out1_2 == 1'b0 ? Switch6_out1_2 :
              Switch7_out1_2);

  assign Switch6_out1_3 = (Bit_Slice10_out1_2 == 1'b0 ? Switch3_out1_2 :
              Switch3_out1_3);

  assign Bit_Slice9_out1_2 = if_opp_Sign_out1[10:7];

  assign Bit_Slice_out1_5 = Bit_Slice9_out1_2[0];

  assign Logical_Operator3_out1_2 = Bit_Slice_out1_5 | Logical_Operator2_out1_2;

  assign Bit_Slice1_out1_5 = Bit_Slice9_out1_2[1];

  assign Logical_Operator_out1_6 = Bit_Slice1_out1_5 | Logical_Operator3_out1_2;

  assign Switch6_out1_4 = (Bit_Slice14_out1_2 == 1'b0 ? Logical_Operator3_out1_2 :
              Logical_Operator_out1_6);

  assign Bit_Slice2_out1_5 = Bit_Slice9_out1_2[2];

  assign Logical_Operator1_out1_6 = Bit_Slice2_out1_5 | Logical_Operator_out1_6;

  assign Bit_Slice3_out1_4 = Bit_Slice9_out1_2[3];

  assign Logical_Operator2_out1_3 = Bit_Slice3_out1_4 | Logical_Operator1_out1_6;

  assign Switch7_out1_3 = (Bit_Slice14_out1_2 == 1'b0 ? Logical_Operator1_out1_6 :
              Logical_Operator2_out1_3);

  assign Switch3_out1_4 = (Bit_Slice11_out1_2 == 1'b0 ? Switch6_out1_4 :
              Switch7_out1_3);

  assign Bit_Slice3_out1_5 = if_opp_Sign_out1[14:11];

  assign Bit_Slice_out1_6 = Bit_Slice3_out1_5[0];

  assign Logical_Operator3_out1_3 = Bit_Slice_out1_6 | Logical_Operator2_out1_3;

  assign Bit_Slice1_out1_6 = Bit_Slice3_out1_5[1];

  assign Logical_Operator_out1_7 = Bit_Slice1_out1_6 | Logical_Operator3_out1_3;

  assign Switch6_out1_5 = (Bit_Slice14_out1_2 == 1'b0 ? Logical_Operator3_out1_3 :
              Logical_Operator_out1_7);

  assign Bit_Slice2_out1_6 = Bit_Slice3_out1_5[2];

  assign Logical_Operator1_out1_7 = Bit_Slice2_out1_6 | Logical_Operator_out1_7;

  assign Bit_Slice3_out1_6 = Bit_Slice3_out1_5[3];

  assign Logical_Operator2_out1_4 = Bit_Slice3_out1_6 | Logical_Operator1_out1_7;

  assign Switch7_out1_4 = (Bit_Slice14_out1_2 == 1'b0 ? Logical_Operator1_out1_7 :
              Logical_Operator2_out1_4);

  assign Switch3_out1_5 = (Bit_Slice11_out1_2 == 1'b0 ? Switch6_out1_5 :
              Switch7_out1_4);

  assign Switch7_out1_5 = (Bit_Slice10_out1_2 == 1'b0 ? Switch3_out1_4 :
              Switch3_out1_5);

  assign Switch3_out1_6 = (Bit_Slice12_out1_2 == 1'b0 ? Switch6_out1_3 :
              Switch7_out1_5);

  assign Bit_Slice4_out1_1 = if_opp_Sign_out1[18:15];

  assign Bit_Slice_out1_7 = Bit_Slice4_out1_1[0];

  assign Logical_Operator3_out1_4 = Bit_Slice_out1_7 | Logical_Operator2_out1_4;

  assign Bit_Slice1_out1_7 = Bit_Slice4_out1_1[1];

  assign Logical_Operator_out1_8 = Bit_Slice1_out1_7 | Logical_Operator3_out1_4;

  assign Switch6_out1_6 = (Bit_Slice14_out1_2 == 1'b0 ? Logical_Operator3_out1_4 :
              Logical_Operator_out1_8);

  assign Bit_Slice2_out1_7 = Bit_Slice4_out1_1[2];

  assign Logical_Operator1_out1_8 = Bit_Slice2_out1_7 | Logical_Operator_out1_8;

  assign Bit_Slice3_out1_7 = Bit_Slice4_out1_1[3];

  assign Logical_Operator2_out1_5 = Bit_Slice3_out1_7 | Logical_Operator1_out1_8;

  assign Switch7_out1_6 = (Bit_Slice14_out1_2 == 1'b0 ? Logical_Operator1_out1_8 :
              Logical_Operator2_out1_5);

  assign Switch3_out1_7 = (Bit_Slice11_out1_2 == 1'b0 ? Switch6_out1_6 :
              Switch7_out1_6);

  assign Bit_Slice5_out1_2 = if_opp_Sign_out1[22:19];

  assign Bit_Slice_out1_8 = Bit_Slice5_out1_2[0];

  assign Logical_Operator3_out1_5 = Bit_Slice_out1_8 | Logical_Operator2_out1_5;

  assign Bit_Slice1_out1_8 = Bit_Slice5_out1_2[1];

  assign Logical_Operator_out1_9 = Bit_Slice1_out1_8 | Logical_Operator3_out1_5;

  assign Switch6_out1_7 = (Bit_Slice14_out1_2 == 1'b0 ? Logical_Operator3_out1_5 :
              Logical_Operator_out1_9);

  assign Bit_Slice2_out1_8 = Bit_Slice5_out1_2[2];

  assign Logical_Operator1_out1_9 = Bit_Slice2_out1_8 | Logical_Operator_out1_9;

  assign Bit_Slice3_out1_8 = Bit_Slice5_out1_2[3];

  assign Logical_Operator2_out1_6 = Bit_Slice3_out1_8 | Logical_Operator1_out1_9;

  assign Switch7_out1_7 = (Bit_Slice14_out1_2 == 1'b0 ? Logical_Operator1_out1_9 :
              Logical_Operator2_out1_6);

  assign Switch3_out1_8 = (Bit_Slice11_out1_2 == 1'b0 ? Switch6_out1_7 :
              Switch7_out1_7);

  assign Switch6_out1_8 = (Bit_Slice10_out1_2 == 1'b0 ? Switch3_out1_7 :
              Switch3_out1_8);

  assign Bit_Slice6_out1_1 = if_opp_Sign_out1[26:23];

  assign Bit_Slice_out1_9 = Bit_Slice6_out1_1[0];

  assign Logical_Operator3_out1_6 = Bit_Slice_out1_9 | Logical_Operator2_out1_6;

  assign Bit_Slice1_out1_9 = Bit_Slice6_out1_1[1];

  assign Logical_Operator_out1_10 = Bit_Slice1_out1_9 | Logical_Operator3_out1_6;

  assign Switch6_out1_9 = (Bit_Slice14_out1_2 == 1'b0 ? Logical_Operator3_out1_6 :
              Logical_Operator_out1_10);

  assign Bit_Slice2_out1_9 = Bit_Slice6_out1_1[2];

  assign Logical_Operator1_out1_10 = Bit_Slice2_out1_9 | Logical_Operator_out1_10;

  assign Bit_Slice3_out1_9 = Bit_Slice6_out1_1[3];

  assign Logical_Operator2_out1_7 = Bit_Slice3_out1_9 | Logical_Operator1_out1_10;

  assign Switch7_out1_8 = (Bit_Slice14_out1_2 == 1'b0 ? Logical_Operator1_out1_10 :
              Logical_Operator2_out1_7);

  assign Switch3_out1_9 = (Bit_Slice11_out1_2 == 1'b0 ? Switch6_out1_9 :
              Switch7_out1_8);

  assign Bit_Slice1_out1_10 = if_opp_Sign_out1[27];

  assign Logical_Operator_out1_11 =  ~ Bit_Slice1_out1_10;

  assign Logical_Operator1_out1_11 = Logical_Operator_out1_11 & Logical_Operator2_out1_7;

  assign Switch7_out1_9 = (Bit_Slice10_out1_2 == 1'b0 ? Switch3_out1_9 :
              Logical_Operator1_out1_11);

  assign Switch3_out1_10 = (Bit_Slice12_out1_2 == 1'b0 ? Switch6_out1_8 :
              Switch7_out1_9);

  assign Switch2_out1_2 = (Bit_Slice13_out1_2 == 1'b0 ? Switch3_out1_6 :
              Switch3_out1_10);

  always @(posedge clk or posedge reset)
    begin : Delay_4_process
      if (reset == 1'b1) begin
        Delay_out1_4 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay_out1_4 <= Switch2_out1_2;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay12_process
      if (reset == 1'b1) begin
        Delay12_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay12_out1 <= Delay_out1_4;
        end
      end
    end

  assign BitSlice1_out1 = mant_a_ext_mant_b_shifted_out1[0];

  assign sticky_bitget_Sum_1_out1 = BitSlice1_out1 | Delay_out1_4;

  always @(posedge clk or posedge reset)
    begin : Delay4_2_process
      if (reset == 1'b1) begin
        Delay4_out1_2 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay4_out1_2 <= sticky_bitget_Sum_1_out1;
        end
      end
    end

  assign if_bitget_Sum_Sum_WordLength_2_out1 = (Delay3_out1_1 == 1'b0 ? Delay12_out1 :
              Delay4_out1_2);

  assign BitSlice_out1_1 = BitSlice6_out1[0];

  assign BitSlice1_out1_1 = BitSlice6_out1[1];

  always @(posedge clk or posedge reset)
    begin : Delay19_process
      if (reset == 1'b1) begin
        Delay19_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay19_out1 <= if_bitget_Sum_Sum_WordLength_2_out1;
        end
      end
    end

  assign sticky_bitget_Sum_1_out1_1 = BitSlice5_out1 | Delay19_out1;

  assign alpha_bitget_Mant_tmp_2_0_out1 = BitSlice1_out1_1 | sticky_bitget_Sum_1_out1_1;

  assign alpha_bitget_Mant_tmp_1_0_out1 = BitSlice_out1_1 & alpha_bitget_Mant_tmp_2_0_out1;

  assign alpha0_out1_2 = 1'b0;

  assign BitSlice4_out1 = BitSlice6_out1[23:1];

  assign Bit_Concat_out1_3 = {alpha0_out1_2, BitSlice4_out1};

  assign cast_2_like_Mant_tmp_out1 = 24'b000000000000000000000001;

  assign Mant_tmp_cast_2_like_Man_out1 = Bit_Concat_out1_3 + cast_2_like_Mant_tmp_out1;

  assign if_bitget_Mant_tmp_1_0_out1 = (alpha_bitget_Mant_tmp_1_0_out1 == 1'b0 ? Bit_Concat_out1_3 :
              Mant_tmp_cast_2_like_Man_out1);

  assign BitSlice2_out1 = if_bitget_Mant_tmp_1_0_out1[23];

  assign BitSlice4_out1_1 = Delay15_out1[25];

  assign C4_out1 = 8'b00000000;

  assign Sum_0_out1 = Delay1_out1_3 == 27'b000000000000000000000000000;

  assign exp_a_cor_shift_length_1 = {3'b0, Delay_out1_3};
  assign exp_a_cor_shift_length_out1 = Delay2_out1_1 - exp_a_cor_shift_length_1;

  assign C2_out1 = 8'b00000001;

  assign if_shift_length_exp_a_cor_out1 = (Logical_Operator1_out1_3 == 1'b0 ? exp_a_cor_shift_length_out1 :
              C2_out1);

  assign BitSlice2_out1_1 = Delay1_out1_3[25];

  assign C3_out1 = 8'b00000000;

  assign if_Sum_0_out1 = (Sum_0_out1 == 1'b0 ? if_shift_length_exp_a_cor_out1 :
              C3_out1);

  assign if_bitget_Sum_Sum_WordLength_1_out1 = (BitSlice2_out1_1 == 1'b0 ? if_Sum_0_out1 :
              Delay2_out1_1);

  assign C_out1_2 = 8'b00000001;

  assign exp_a_cor_1_out1_1 = C_out1_2 + Delay2_out1_1;

  assign if_bitget_Sum_Sum_WordLength_1_out1_1 = (Delay3_out1_1 == 1'b0 ? if_bitget_Sum_Sum_WordLength_1_out1 :
              exp_a_cor_1_out1_1);

  always @(posedge clk or posedge reset)
    begin : Delay14_process
      if (reset == 1'b1) begin
        Delay14_out1 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          Delay14_out1 <= if_bitget_Sum_Sum_WordLength_1_out1_1;
        end
      end
    end

  assign if_bitget_Sum_Sum_WordLength_out1_1 = (BitSlice4_out1_1 == 1'b0 ? C4_out1 :
              Delay14_out1);

  assign cast_1_like_Exp_out1 = 8'b00000001;

  assign Exp_cast_1_like_Exp_out1 = if_bitget_Sum_Sum_WordLength_out1_1 + cast_1_like_Exp_out1;

  assign if_bitget_Mant_tmp_Mant_tmp_Wor_out1 = (BitSlice2_out1 == 1'b0 ? if_bitget_Sum_Sum_WordLength_out1_1 :
              Exp_cast_1_like_Exp_out1);

  assign Exponent_0_out1_2 = if_bitget_Mant_tmp_Mant_tmp_Wor_out1 == 8'b00000000;

  assign BitSlice3_out1_1 = if_bitget_Mant_tmp_1_0_out1[22:0];

  assign Mantissa_0_out1 = BitSlice3_out1_1 == 23'b00000000000000000000000;

  assign alpha_Exponent_0_Mantissa_out1 = Exponent_0_out1_2 & Mantissa_0_out1;

  assign Constant_out1_2 = 1'b0;

  assign Switch_out1_1 = (Delay18_out1 == 1'b0 ? alpha_Exponent_0_Mantissa_out1 :
              Constant_out1_2);

  always @(posedge clk or posedge reset)
    begin : Delay12_1_process
      if (reset == 1'b1) begin
        Delay12_out1_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay12_out1_1 <= if_bitconcat_aExponent_aMantiss_2_out1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay29_process
      if (reset == 1'b1) begin
        Delay29_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay29_out1 <= Delay12_out1_1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay14_1_process
      if (reset == 1'b1) begin
        Delay14_reg <= {2{1'b0}};
      end
      else begin
        if (enb) begin
          Delay14_reg[0] <= Delay29_out1;
          Delay14_reg[1] <= Delay14_reg[0];
        end
      end
    end

  assign Delay14_out1_1 = Delay14_reg[1];

  assign alpha_aSign_1_bSign_1_out1 = if_bitconcat_aExponent_aMantiss_2_out1 & if_bitconcat_aExponent_aMantiss_5_out1;

  always @(posedge clk or posedge reset)
    begin : Delay9_process
      if (reset == 1'b1) begin
        Delay9_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay9_out1 <= alpha_aSign_1_bSign_1_out1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay25_process
      if (reset == 1'b1) begin
        Delay25_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay25_out1 <= Delay9_out1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay13_1_process
      if (reset == 1'b1) begin
        Delay13_reg <= {2{1'b0}};
      end
      else begin
        if (enb) begin
          Delay13_reg[0] <= Delay25_out1;
          Delay13_reg[1] <= Delay13_reg[0];
        end
      end
    end

  assign Delay13_out1_1 = Delay13_reg[1];

  assign if_Exponent_0_Mantissa_out1 = (Switch_out1_1 == 1'b0 ? Delay14_out1_1 :
              Delay13_out1_1);

  always @(posedge clk or posedge reset)
    begin : Delay6_process
      if (reset == 1'b1) begin
        Delay6_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay6_out1 <= if_Exponent_0_Mantissa_out1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay32_process
      if (reset == 1'b1) begin
        Delay32_out1 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          Delay32_out1 <= if_bitconcat_aExponent_aMantiss_out1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay34_process
      if (reset == 1'b1) begin
        Delay34_out1 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          Delay34_out1 <= Delay32_out1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay15_1_process
      if (reset == 1'b1) begin
        for(Delay15_t_1 = 32'sd0; Delay15_t_1 <= 32'sd1; Delay15_t_1 = Delay15_t_1 + 32'sd1) begin
          Delay15_reg[Delay15_t_1] <= 8'b00000000;
        end
      end
      else begin
        if (enb) begin
          for(Delay15_t_0_0 = 32'sd0; Delay15_t_0_0 <= 32'sd1; Delay15_t_0_0 = Delay15_t_0_0 + 32'sd1) begin
            Delay15_reg[Delay15_t_0_0] <= Delay15_reg_next[Delay15_t_0_0];
          end
        end
      end
    end

  assign Delay15_out1_1 = Delay15_reg[1];
  assign Delay15_reg_next[0] = Delay34_out1;
  assign Delay15_reg_next[1] = Delay15_reg[0];

  assign if_aExponent_cfType_Exponent_out1 = (Delay18_out1 == 1'b0 ? if_bitget_Mant_tmp_Mant_tmp_Wor_out1 :
              Delay15_out1_1);

  always @(posedge clk or posedge reset)
    begin : Delay7_process
      if (reset == 1'b1) begin
        Delay7_out1 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          Delay7_out1 <= if_aExponent_cfType_Exponent_out1;
        end
      end
    end

  assign opp_signs_exp_b_cfType_out1 = bitxor_out1 & exp_b_cfType_Exponent_Inf_o_out1;

  assign mant_a_0_out1 = if_bitconcat_aExponent_aMantiss_1_out1 != 23'b00000000000000000000000;

  assign alpha_mant_a_0_opp_signs_out1 = opp_signs_exp_b_cfType_out1 | mant_a_0_out1;

  assign BitSet_out1 = if_bitconcat_aExponent_aMantiss_1_out1 | 23'b10000000000000000000000;

  assign if_mant_a_0_opp_signs_out1 = (alpha_mant_a_0_opp_signs_out1 == 1'b0 ? if_bitconcat_aExponent_aMantiss_1_out1 :
              BitSet_out1);

  always @(posedge clk or posedge reset)
    begin : Delay2_3_process
      if (reset == 1'b1) begin
        Delay2_out1_3 <= 23'b00000000000000000000000;
      end
      else begin
        if (enb) begin
          Delay2_out1_3 <= if_mant_a_0_opp_signs_out1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay38_process
      if (reset == 1'b1) begin
        Delay38_out1 <= 23'b00000000000000000000000;
      end
      else begin
        if (enb) begin
          Delay38_out1 <= Delay2_out1_3;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay17_process
      if (reset == 1'b1) begin
        for(Delay17_t_1 = 32'sd0; Delay17_t_1 <= 32'sd1; Delay17_t_1 = Delay17_t_1 + 32'sd1) begin
          Delay17_reg[Delay17_t_1] <= 23'b00000000000000000000000;
        end
      end
      else begin
        if (enb) begin
          for(Delay17_t_0_0 = 32'sd0; Delay17_t_0_0 <= 32'sd1; Delay17_t_0_0 = Delay17_t_0_0 + 32'sd1) begin
            Delay17_reg[Delay17_t_0_0] <= Delay17_reg_next[Delay17_t_0_0];
          end
        end
      end
    end

  assign Delay17_out1 = Delay17_reg[1];
  assign Delay17_reg_next[0] = Delay38_out1;
  assign Delay17_reg_next[1] = Delay17_reg[0];

  assign if_aExponent_cfType_Exponent_1_out1 = (Delay18_out1 == 1'b0 ? BitSlice3_out1_1 :
              Delay17_out1);

  always @(posedge clk or posedge reset)
    begin : Delay8_process
      if (reset == 1'b1) begin
        Delay8_out1 <= 23'b00000000000000000000000;
      end
      else begin
        if (enb) begin
          Delay8_out1 <= if_aExponent_cfType_Exponent_1_out1;
        end
      end
    end

  // Combine FP sign, exponent, mantissa into 32 bit word
  assign nfp_out_pack = {Delay6_out1, Delay7_out1, Delay8_out1};

  assign nfp_out = nfp_out_pack;

endmodule  // nfp_add_single

