// -------------------------------------------------------------
// 
// File Name: hdlsrc/MAC/nfp_mul_single.v
// Created: 2026-09-05 16:51:47
// 
// Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: nfp_mul_single
// Source Path: MAC/FP16/nfp_mul_single
// Hierarchy Level: 1
// Model version: 1.6
// 
// {Latency Strategy = "Max", Denormal Handling = "off"}
// {Mantissa Multiply Strategy = "PartMultiplierPartAddShift"}
// {Part Add Shift Multiplier Size = "18x24"}
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module nfp_mul_single
          (clk,
           reset,
           enb,
           nfp_in1,
           nfp_in2,
           nfp_out);


  input   clk;
  input   reset;
  input   enb;
  input   [31:0] nfp_in1;  // ufix32
  input   [31:0] nfp_in2;  // ufix32
  output  [31:0] nfp_out;  // ufix32


  wire BS;  // ufix1
  wire [7:0] BE;  // ufix8
  wire [22:0] BM;  // ufix23
  wire Compare_To_Constant1_out1;
  reg  Delay16_out1;
  wire Compare_To_Zero3_out1;
  reg  Delay14_out1;
  wire Logical_Operator1_out1;
  wire AS;  // ufix1
  wire [7:0] AE;  // ufix8
  wire [22:0] AM;  // ufix23
  wire Compare_To_Constant_out1;
  reg  Delay21_out1;
  wire Compare_To_Zero2_out1;
  reg  Delay19_out1;
  wire Logical_Operator_out1;
  reg  Delay3_out1;
  reg  Delay7_out1;
  wire Logical_Operator_out1_1;
  wire Switch_out1;
  wire Switch1_out1;
  reg  [6:0] Delay_reg;  // ufix1 [7]
  wire Delay_out1;
  wire Constant8_out1;  // ufix1
  wire [7:0] Constant7_out1;  // uint8
  wire Relational_Operator_out1;
  reg  Delay4_out1;
  wire Logical_Operator2_out1;
  wire Logical_Operator_out1_2;  // ufix1
  wire [7:0] Add_out1;  // uint8
  reg [7:0] Delay3_out1_1;  // uint8
  wire [7:0] Add_1;  // ufix8
  wire [7:0] Constant6_out1;  // uint8
  wire Logical_Operator3_out1;
  wire Compare_To_Zero1_out1;
  reg  Delay20_out1;
  wire Constant3_out1;  // ufix1
  wire Constant2_out1;  // ufix1
  wire Switch2_out1;  // ufix1
  wire Logical_Operator_out1_3;
  reg [22:0] Delay8_out1;  // ufix23
  wire [23:0] Bit_Concat1_out1;  // ufix24
  wire [23:0] Constant4_out1;  // ufix24
  wire [23:0] Switch3_out1;  // ufix24
  wire [17:0] BitSlice9_out1;  // ufix18
  reg [17:0] Delay24_out1;  // ufix18
  wire Compare_To_Zero_out1;
  reg  Delay23_out1;
  wire Constant1_out1;  // ufix1
  wire Constant_out1;  // ufix1
  wire Switch1_out1_1;  // ufix1
  reg [22:0] Delay6_out1;  // ufix23
  wire [23:0] Bit_Concat_out1;  // ufix24
  wire [23:0] Constant5_out1;  // ufix24
  wire [23:0] Switch_out1_1;  // ufix24
  reg [23:0] M_to_1_M_out1;  // ufix24
  wire [41:0] Product_out1;  // ufix42
  reg [41:0] Delay8_reg [0:1];  // ufix42 [2]
  wire [41:0] Delay8_reg_next [0:1];  // ufix42 [2]
  wire [41:0] Delay8_out1_1;  // ufix42
  wire [1:0] BitSlice5_out1;  // ufix2
  reg [1:0] Delay14_out1_1;  // ufix2
  wire [7:0] DTC6_out1;  // uint8
  wire [25:0] C1_out1;  // ufix26
  wire Constant1_out1_1;
  wire [24:0] Bit_Concat2_out1;  // ufix25
  wire [25:0] DTC6_out1_1;  // ufix26
  reg [24:0] Delay2_out1;  // ufix25
  wire [25:0] DTC4_out1;  // ufix26
  wire [22:0] Bit_Slice_out1;  // ufix23
  wire [31:0] Sum1_add_temp;  // ufix32
  wire [31:0] Sum1_1;  // ufix32
  wire [31:0] Sum1_2;  // ufix32
  wire [24:0] Sum1_out1;  // ufix25
  wire Bit_Slice1_out1;  // ufix1
  wire [25:0] Bit_Concat1_out1_1;  // ufix26
  reg [25:0] Delay3_out1_2;  // ufix26
  wire [25:0] LUT4_out1 [0:3];  // ufix26 [4]
  wire [25:0] Selector5_out1;  // ufix26
  reg [25:0] Delay6_reg [0:1];  // ufix26 [2]
  wire [25:0] Delay6_reg_next [0:1];  // ufix26 [2]
  wire [25:0] Delay6_out1_1;  // ufix26
  wire [23:0] Bit_Slice3_out1;  // ufix24
  wire [42:0] Sum2_1;  // ufix43
  wire [42:0] Sum2_2;  // ufix43
  wire [42:0] Sum2_out1;  // ufix43
  wire [1:0] Bit_Slice4_out1;  // ufix2
  wire [44:0] Bit_Concat4_out1;  // ufix45
  reg [44:0] Delay4_out1_1;  // ufix45
  wire [1:0] BitSlice4_out1;  // ufix2
  reg [1:0] Delay13_out1;  // ufix2
  wire [7:0] DTC7_out1;  // uint8
  wire [25:0] Selector4_out1;  // ufix26
  reg [25:0] Delay5_reg [0:1];  // ufix26 [2]
  wire [25:0] Delay5_reg_next [0:1];  // ufix26 [2]
  wire [25:0] Delay5_out1;  // ufix26
  wire [1:0] BitSlice1_out1;  // ufix2
  reg [1:0] Delay12_out1;  // ufix2
  wire [7:0] DTC8_out1;  // uint8
  wire [25:0] Selector3_out1;  // ufix26
  reg [25:0] Delay3_reg [0:1];  // ufix26 [2]
  wire [25:0] Delay3_reg_next [0:1];  // ufix26 [2]
  wire [25:0] Delay3_out1_3;  // ufix26
  wire [23:0] Bit_Slice1_out1_1;  // ufix24
  wire [31:0] Sum31_add_temp;  // ufix32
  wire [31:0] Sum31_1;  // ufix32
  wire [31:0] Sum31_2;  // ufix32
  wire [26:0] Sum31_out1;  // ufix27
  wire [1:0] Bit_Slice2_out1;  // ufix2
  wire [28:0] Bit_Concat3_out1;  // ufix29
  reg [28:0] Delay19_out1_1;  // ufix29
  wire [24:0] Bit_Slice5_out1;  // ufix25
  wire [45:0] FinalSum1_1;  // ufix46
  wire [45:0] FinalSum1_2;  // ufix46
  wire [45:0] FinalSum1_out1;  // ufix46
  wire [3:0] Bit_Slice6_out1;  // ufix4
  wire [49:0] Bit_Concat1_out1_2;  // ufix50
  wire [47:0] Data_Type_Conversion_out1;  // ufix48
  wire Constant1_out1_2;
  wire [48:0] Bit_Concat_out1_1;  // ufix49
  reg [48:0] Delay3_out1_4;  // ufix49
  wire Bit_Slice1_out1_2;  // ufix1
  wire Logical_Operator1_out1_1;
  reg  Delay3_out1_5;
  wire Logical_Operator3_out1_1;
  wire Logical_Operator_out1_4;
  reg  Delay1_out1;
  wire Logical_Operator2_out1_1;
  reg  [3:0] Delay8_reg_1;  // ufix1 [4]
  wire Delay8_out1_2;
  reg [7:0] Delay4_out1_2;  // uint8
  reg [7:0] Delay5_out1_1;  // uint8
  wire [31:0] Subtract_add_temp;  // ufix32
  wire [31:0] Subtract_1;  // ufix32
  wire [31:0] Subtract_2;  // ufix32
  wire [8:0] Subtract_out1;  // ufix9
  reg [8:0] Delay_out1_1;  // ufix9
  wire [6:0] Constant2_out1_1;  // ufix7
  wire Constant1_out1_3;
  wire Constant3_out1_1;
  wire Switch_out1_2;
  wire [7:0] Bit_Concat1_out1_3;  // uint8
  wire Switch1_out1_2;
  wire [7:0] Bit_Concat_out1_2;  // uint8
  wire [31:0] Add1_add_temp;  // ufix32
  wire [31:0] Add1_1;  // ufix32
  wire [31:0] Add1_2;  // ufix32
  wire [8:0] Add1_out1;  // ufix9
  reg [8:0] Delay2_out1_1;  // ufix9
  wire signed [31:0] Subtract2_sub_temp;  // sfix32
  wire signed [31:0] Subtract2_1;  // sfix32
  wire signed [31:0] Subtract2_2;  // sfix32
  wire signed [9:0] Subtract2_out1;  // sfix10
  wire signed [9:0] Constant4_out1_1;  // sfix10
  wire signed [9:0] Switch2_out1_1;  // sfix10
  reg signed [9:0] Delay4_reg [0:3];  // sfix10 [4]
  reg signed [9:0] Delay4_reg_next [0:3];  // sfix10 [4]
  reg signed [9:0] Delay4_out1_3;  // sfix10
  wire signed [9:0] Constant_out1_1;  // sfix10
  wire signed [9:0] Switch1_out1_3;  // sfix10
  wire signed [31:0] Add_add_temp;  // sfix32
  wire signed [31:0] Add_3;  // sfix32
  wire signed [31:0] Add_4;  // sfix32
  wire signed [9:0] Add_out1_1;  // sfix10
  wire Compare_To_Constant_out1_1;
  wire signed [9:0] Constant1_out1_4;  // sfix10
  wire signed [9:0] Switch2_out1_2;  // sfix10
  reg signed [9:0] Delay18_out1;  // sfix10
  wire Compare_To_Constant1_out1_1;
  wire Logical_Operator1_out1_2;
  wire Logical_Operator4_out1;
  wire Logical_Operator7_out1;
  wire Logical_Operator5_out1;
  wire Logical_Operator6_out1;
  wire Logical_Operator8_out1;
  wire Inf_Zero_out1;
  wire Logical_Operator2_out1_2;
  wire Logical_Operator10_out1;
  reg  [5:0] Delay13_reg;  // ufix1 [6]
  wire Delay13_out1_1;
  wire Logical_Operator_out1_5;
  wire Compare_To_Constant_out1_2;
  wire [7:0] Constant1_out1_5;  // uint8
  wire [48:0] Bit_Shift_out1;  // ufix49
  wire [48:0] Switch_out1_3;  // ufix49
  wire [47:0] Bit_Slice_out1_1;  // ufix48
  wire [1:0] Bit_Slice2_out1_1;  // ufix2
  wire Bit_Slice4_out1_1;  // ufix1
  wire [21:0] Bit_Slice1_out1_3;  // ufix22
  wire Bit_Reduce_out1;  // ufix1
  wire Bit_Slice5_out1_1;  // ufix1
  wire Bit_Slice3_out1_1;  // ufix1
  wire Logical_Operator1_out1_3;
  wire Logical_Operator_out1_6;
  wire [22:0] Bit_Slice1_out1_4;  // ufix23
  reg  Delay1_out1_1;
  reg [22:0] Delay2_out1_2;  // ufix23
  wire [23:0] Delay2_out1_dtc;  // ufix24
  wire Constant_out1_2;
  wire [31:0] Add_add_temp_1;  // ufix32
  wire [31:0] Add_6;  // ufix32
  wire [31:0] Add_7;  // ufix32
  wire [23:0] Add_out1_2;  // ufix24
  reg [23:0] Delay_out1_2;  // ufix24
  wire [23:0] Switch_out1_4;  // ufix24
  wire Bit_Slice2_out1_2;  // ufix1
  wire [31:0] Add1_add_temp_1;  // ufix32
  wire [31:0] Add1_4;  // ufix32
  wire [31:0] Add1_5;  // ufix32
  wire [7:0] Add1_out1_1;  // uint8
  wire signed [31:0] Add_add_temp_2;  // sfix32
  wire signed [31:0] Add_9;  // sfix32
  wire signed [31:0] Add_10;  // sfix32
  wire [7:0] Add_out1_3;  // uint8
  wire [7:0] Constant1_out1_6;  // uint8
  wire [7:0] Switch1_out1_4;  // uint8
  wire [7:0] Constant4_out1_2;  // uint8
  wire [7:0] Switch4_out1;  // uint8
  wire [7:0] Switch6_out1;  // uint8
  reg [7:0] Delay1_out1_2;  // uint8
  wire [22:0] Bit_Slice4_out1_2;  // ufix23
  wire [22:0] Bit_Shift_out1_1;  // ufix23
  wire [22:0] Switch1_out1_5;  // ufix23
  wire [22:0] Constant2_out1_2;  // ufix23
  wire [22:0] Switch2_out1_3;  // ufix23
  wire [22:0] Constant5_out1_1;  // ufix23
  wire [22:0] Bit_Set_out1;  // ufix23
  wire [22:0] Switch7_out1;  // ufix23
  wire [22:0] Switch5_out1;  // ufix23
  reg [22:0] Delay2_out1_3;  // ufix23
  wire [31:0] nfp_out_pack;  // ufix32
  reg signed [31:0] Delay8_t_0_0;  // int32
  reg signed [31:0] Delay8_t_1;  // int32
  reg signed [31:0] Delay6_t_0_0;  // int32
  reg signed [31:0] Delay6_t_1;  // int32
  reg signed [31:0] Delay5_t_0_0;  // int32
  reg signed [31:0] Delay5_t_1;  // int32
  reg signed [31:0] Delay3_t_0_0;  // int32
  reg signed [31:0] Delay3_t_1;  // int32
  reg signed [31:0] Delay4_t_0_0;  // int32
  reg signed [31:0] Delay4_t_0_1;  // int32
  reg signed [31:0] Delay4_t_1;  // int32


  // Split 32 bit word into FP sign, exponent, mantissa
  assign BS = nfp_in2[31];
  assign BE = nfp_in2[30:23];
  assign BM = nfp_in2[22:0];

  assign Compare_To_Constant1_out1 = BE == 8'b11111111;

  always @(posedge clk or posedge reset)
    begin : Delay16_process
      if (reset == 1'b1) begin
        Delay16_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay16_out1 <= Compare_To_Constant1_out1;
        end
      end
    end

  assign Compare_To_Zero3_out1 = BM != 23'b00000000000000000000000;

  always @(posedge clk or posedge reset)
    begin : Delay14_process
      if (reset == 1'b1) begin
        Delay14_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay14_out1 <= Compare_To_Zero3_out1;
        end
      end
    end

  assign Logical_Operator1_out1 = Delay16_out1 & Delay14_out1;

  // Split 32 bit word into FP sign, exponent, mantissa
  assign AS = nfp_in1[31];
  assign AE = nfp_in1[30:23];
  assign AM = nfp_in1[22:0];

  assign Compare_To_Constant_out1 = AE == 8'b11111111;

  always @(posedge clk or posedge reset)
    begin : Delay21_process
      if (reset == 1'b1) begin
        Delay21_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay21_out1 <= Compare_To_Constant_out1;
        end
      end
    end

  assign Compare_To_Zero2_out1 = AM != 23'b00000000000000000000000;

  always @(posedge clk or posedge reset)
    begin : Delay19_process
      if (reset == 1'b1) begin
        Delay19_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay19_out1 <= Compare_To_Zero2_out1;
        end
      end
    end

  assign Logical_Operator_out1 = Delay21_out1 & Delay19_out1;

  always @(posedge clk or posedge reset)
    begin : Delay3_process
      if (reset == 1'b1) begin
        Delay3_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay3_out1 <= AS;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay7_process
      if (reset == 1'b1) begin
        Delay7_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay7_out1 <= BS;
        end
      end
    end

  assign Logical_Operator_out1_1 = Delay3_out1 ^ Delay7_out1;

  assign Switch_out1 = (Logical_Operator_out1 == 1'b0 ? Logical_Operator_out1_1 :
              Delay3_out1);

  assign Switch1_out1 = (Logical_Operator1_out1 == 1'b0 ? Switch_out1 :
              Delay7_out1);

  always @(posedge clk or posedge reset)
    begin : Delay_process
      if (reset == 1'b1) begin
        Delay_reg <= {7{1'b0}};
      end
      else begin
        if (enb) begin
          Delay_reg[0] <= Switch1_out1;
          Delay_reg[32'sd6:32'sd1] <= Delay_reg[32'sd5:32'sd0];
        end
      end
    end

  assign Delay_out1 = Delay_reg[6];

  assign Constant8_out1 = 1'b1;

  assign Constant7_out1 = 8'b00001000;

  always @(posedge clk or posedge reset)
    begin : Delay4_process
      if (reset == 1'b1) begin
        Delay4_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay4_out1 <= Relational_Operator_out1;
        end
      end
    end

  assign Logical_Operator2_out1 =  ~ Delay4_out1;

  assign Logical_Operator_out1_2 = Constant8_out1 & Logical_Operator2_out1;

  always @(posedge clk or posedge reset)
    begin : Delay3_1_process
      if (reset == 1'b1) begin
        Delay3_out1_1 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          Delay3_out1_1 <= Add_out1;
        end
      end
    end

  assign Add_1 = {7'b0, Logical_Operator_out1_2};
  assign Add_out1 = Delay3_out1_1 + Add_1;

  assign Relational_Operator_out1 = Add_out1 >= Constant7_out1;

  assign Constant6_out1 = 8'b00000000;

  assign Logical_Operator3_out1 =  ~ Logical_Operator1_out1;

  assign Compare_To_Zero1_out1 = BE == 8'b00000000;

  always @(posedge clk or posedge reset)
    begin : Delay20_process
      if (reset == 1'b1) begin
        Delay20_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay20_out1 <= Compare_To_Zero1_out1;
        end
      end
    end

  assign Constant3_out1 = 1'b1;

  assign Constant2_out1 = 1'b0;

  assign Switch2_out1 = (Delay20_out1 == 1'b0 ? Constant3_out1 :
              Constant2_out1);

  assign Logical_Operator_out1_3 = Logical_Operator_out1 & Logical_Operator3_out1;

  always @(posedge clk or posedge reset)
    begin : Delay8_process
      if (reset == 1'b1) begin
        Delay8_out1 <= 23'b00000000000000000000000;
      end
      else begin
        if (enb) begin
          Delay8_out1 <= BM;
        end
      end
    end

  assign Bit_Concat1_out1 = {Switch2_out1, Delay8_out1};

  assign Constant4_out1 = 24'b100000000000000000000000;

  assign Switch3_out1 = (Logical_Operator_out1_3 == 1'b0 ? Bit_Concat1_out1 :
              Constant4_out1);

  assign BitSlice9_out1 = Switch3_out1[23:6];

  always @(posedge clk or posedge reset)
    begin : Delay24_process
      if (reset == 1'b1) begin
        Delay24_out1 <= 18'b000000000000000000;
      end
      else begin
        if (enb) begin
          Delay24_out1 <= BitSlice9_out1;
        end
      end
    end

  assign Compare_To_Zero_out1 = AE == 8'b00000000;

  always @(posedge clk or posedge reset)
    begin : Delay23_process
      if (reset == 1'b1) begin
        Delay23_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay23_out1 <= Compare_To_Zero_out1;
        end
      end
    end

  assign Constant1_out1 = 1'b1;

  assign Constant_out1 = 1'b0;

  assign Switch1_out1_1 = (Delay23_out1 == 1'b0 ? Constant1_out1 :
              Constant_out1);

  always @(posedge clk or posedge reset)
    begin : Delay6_process
      if (reset == 1'b1) begin
        Delay6_out1 <= 23'b00000000000000000000000;
      end
      else begin
        if (enb) begin
          Delay6_out1 <= AM;
        end
      end
    end

  assign Bit_Concat_out1 = {Switch1_out1_1, Delay6_out1};

  assign Constant5_out1 = 24'b100000000000000000000000;

  assign Switch_out1_1 = (Logical_Operator1_out1 == 1'b0 ? Bit_Concat_out1 :
              Constant5_out1);

  always @(posedge clk or posedge reset)
    begin : reduced_process
      if (reset == 1'b1) begin
        M_to_1_M_out1 <= 24'b000000000000000000000000;
      end
      else begin
        if (enb) begin
          M_to_1_M_out1 <= Switch_out1_1;
        end
      end
    end

  assign Product_out1 = Delay24_out1 * M_to_1_M_out1;

  always @(posedge clk or posedge reset)
    begin : Delay8_1_process
      if (reset == 1'b1) begin
        for(Delay8_t_1 = 32'sd0; Delay8_t_1 <= 32'sd1; Delay8_t_1 = Delay8_t_1 + 32'sd1) begin
          Delay8_reg[Delay8_t_1] <= 42'h00000000000;
        end
      end
      else begin
        if (enb) begin
          for(Delay8_t_0_0 = 32'sd0; Delay8_t_0_0 <= 32'sd1; Delay8_t_0_0 = Delay8_t_0_0 + 32'sd1) begin
            Delay8_reg[Delay8_t_0_0] <= Delay8_reg_next[Delay8_t_0_0];
          end
        end
      end
    end

  assign Delay8_out1_1 = Delay8_reg[1];
  assign Delay8_reg_next[0] = Product_out1;
  assign Delay8_reg_next[1] = Delay8_reg[0];

  assign BitSlice5_out1 = Switch3_out1[5:4];

  always @(posedge clk or posedge reset)
    begin : Delay14_1_process
      if (reset == 1'b1) begin
        Delay14_out1_1 <= 2'b00;
      end
      else begin
        if (enb) begin
          Delay14_out1_1 <= BitSlice5_out1;
        end
      end
    end

  assign DTC6_out1 = {6'b0, Delay14_out1_1};

  assign C1_out1 = 26'b00000000000000000000000000;

  assign Constant1_out1_1 = 1'b0;

  assign Bit_Concat2_out1 = {Switch_out1_1, Constant1_out1_1};

  assign DTC6_out1_1 = {2'b0, M_to_1_M_out1};

  always @(posedge clk or posedge reset)
    begin : Delay2_process
      if (reset == 1'b1) begin
        Delay2_out1 <= 25'b0000000000000000000000000;
      end
      else begin
        if (enb) begin
          Delay2_out1 <= Bit_Concat2_out1;
        end
      end
    end

  assign DTC4_out1 = {1'b0, Delay2_out1};

  assign Bit_Slice_out1 = Switch_out1_1[23:1];

  assign Sum1_1 = {8'b0, Switch_out1_1};
  assign Sum1_2 = {9'b0, Bit_Slice_out1};
  assign Sum1_add_temp = Sum1_1 + Sum1_2;
  assign Sum1_out1 = Sum1_add_temp[24:0];

  assign Bit_Slice1_out1 = Switch_out1_1[0];

  assign Bit_Concat1_out1_1 = {Sum1_out1, Bit_Slice1_out1};

  always @(posedge clk or posedge reset)
    begin : Delay3_2_process
      if (reset == 1'b1) begin
        Delay3_out1_2 <= 26'b00000000000000000000000000;
      end
      else begin
        if (enb) begin
          Delay3_out1_2 <= Bit_Concat1_out1_1;
        end
      end
    end

  assign LUT4_out1[0] = C1_out1;
  assign LUT4_out1[1] = DTC6_out1_1;
  assign LUT4_out1[2] = DTC4_out1;
  assign LUT4_out1[3] = Delay3_out1_2;

  assign Selector5_out1 = (DTC6_out1 == 8'b00000000 ? LUT4_out1[0] :
              (DTC6_out1 == 8'b00000001 ? LUT4_out1[1] :
              (DTC6_out1 == 8'b00000010 ? LUT4_out1[2] :
              LUT4_out1[3])));

  always @(posedge clk or posedge reset)
    begin : Delay6_1_process
      if (reset == 1'b1) begin
        for(Delay6_t_1 = 32'sd0; Delay6_t_1 <= 32'sd1; Delay6_t_1 = Delay6_t_1 + 32'sd1) begin
          Delay6_reg[Delay6_t_1] <= 26'b00000000000000000000000000;
        end
      end
      else begin
        if (enb) begin
          for(Delay6_t_0_0 = 32'sd0; Delay6_t_0_0 <= 32'sd1; Delay6_t_0_0 = Delay6_t_0_0 + 32'sd1) begin
            Delay6_reg[Delay6_t_0_0] <= Delay6_reg_next[Delay6_t_0_0];
          end
        end
      end
    end

  assign Delay6_out1_1 = Delay6_reg[1];
  assign Delay6_reg_next[0] = Selector5_out1;
  assign Delay6_reg_next[1] = Delay6_reg[0];

  assign Bit_Slice3_out1 = Delay6_out1_1[25:2];

  assign Sum2_1 = {1'b0, Delay8_out1_1};
  assign Sum2_2 = {19'b0, Bit_Slice3_out1};
  assign Sum2_out1 = Sum2_1 + Sum2_2;

  assign Bit_Slice4_out1 = Delay6_out1_1[1:0];

  assign Bit_Concat4_out1 = {Sum2_out1, Bit_Slice4_out1};

  always @(posedge clk or posedge reset)
    begin : Delay4_1_process
      if (reset == 1'b1) begin
        Delay4_out1_1 <= 45'h000000000000;
      end
      else begin
        if (enb) begin
          Delay4_out1_1 <= Bit_Concat4_out1;
        end
      end
    end

  assign BitSlice4_out1 = Switch3_out1[3:2];

  always @(posedge clk or posedge reset)
    begin : Delay13_process
      if (reset == 1'b1) begin
        Delay13_out1 <= 2'b00;
      end
      else begin
        if (enb) begin
          Delay13_out1 <= BitSlice4_out1;
        end
      end
    end

  assign DTC7_out1 = {6'b0, Delay13_out1};

  assign Selector4_out1 = (DTC7_out1 == 8'b00000000 ? LUT4_out1[0] :
              (DTC7_out1 == 8'b00000001 ? LUT4_out1[1] :
              (DTC7_out1 == 8'b00000010 ? LUT4_out1[2] :
              LUT4_out1[3])));

  always @(posedge clk or posedge reset)
    begin : Delay5_process
      if (reset == 1'b1) begin
        for(Delay5_t_1 = 32'sd0; Delay5_t_1 <= 32'sd1; Delay5_t_1 = Delay5_t_1 + 32'sd1) begin
          Delay5_reg[Delay5_t_1] <= 26'b00000000000000000000000000;
        end
      end
      else begin
        if (enb) begin
          for(Delay5_t_0_0 = 32'sd0; Delay5_t_0_0 <= 32'sd1; Delay5_t_0_0 = Delay5_t_0_0 + 32'sd1) begin
            Delay5_reg[Delay5_t_0_0] <= Delay5_reg_next[Delay5_t_0_0];
          end
        end
      end
    end

  assign Delay5_out1 = Delay5_reg[1];
  assign Delay5_reg_next[0] = Selector4_out1;
  assign Delay5_reg_next[1] = Delay5_reg[0];

  assign BitSlice1_out1 = Switch3_out1[1:0];

  always @(posedge clk or posedge reset)
    begin : Delay12_process
      if (reset == 1'b1) begin
        Delay12_out1 <= 2'b00;
      end
      else begin
        if (enb) begin
          Delay12_out1 <= BitSlice1_out1;
        end
      end
    end

  assign DTC8_out1 = {6'b0, Delay12_out1};

  assign Selector3_out1 = (DTC8_out1 == 8'b00000000 ? LUT4_out1[0] :
              (DTC8_out1 == 8'b00000001 ? LUT4_out1[1] :
              (DTC8_out1 == 8'b00000010 ? LUT4_out1[2] :
              LUT4_out1[3])));

  always @(posedge clk or posedge reset)
    begin : Delay3_3_process
      if (reset == 1'b1) begin
        for(Delay3_t_1 = 32'sd0; Delay3_t_1 <= 32'sd1; Delay3_t_1 = Delay3_t_1 + 32'sd1) begin
          Delay3_reg[Delay3_t_1] <= 26'b00000000000000000000000000;
        end
      end
      else begin
        if (enb) begin
          for(Delay3_t_0_0 = 32'sd0; Delay3_t_0_0 <= 32'sd1; Delay3_t_0_0 = Delay3_t_0_0 + 32'sd1) begin
            Delay3_reg[Delay3_t_0_0] <= Delay3_reg_next[Delay3_t_0_0];
          end
        end
      end
    end

  assign Delay3_out1_3 = Delay3_reg[1];
  assign Delay3_reg_next[0] = Selector3_out1;
  assign Delay3_reg_next[1] = Delay3_reg[0];

  assign Bit_Slice1_out1_1 = Delay3_out1_3[25:2];

  assign Sum31_1 = {6'b0, Delay5_out1};
  assign Sum31_2 = {8'b0, Bit_Slice1_out1_1};
  assign Sum31_add_temp = Sum31_1 + Sum31_2;
  assign Sum31_out1 = Sum31_add_temp[26:0];

  assign Bit_Slice2_out1 = Delay3_out1_3[1:0];

  assign Bit_Concat3_out1 = {Sum31_out1, Bit_Slice2_out1};

  always @(posedge clk or posedge reset)
    begin : Delay19_1_process
      if (reset == 1'b1) begin
        Delay19_out1_1 <= 29'b00000000000000000000000000000;
      end
      else begin
        if (enb) begin
          Delay19_out1_1 <= Bit_Concat3_out1;
        end
      end
    end

  assign Bit_Slice5_out1 = Delay19_out1_1[28:4];

  assign FinalSum1_1 = {1'b0, Delay4_out1_1};
  assign FinalSum1_2 = {21'b0, Bit_Slice5_out1};
  assign FinalSum1_out1 = FinalSum1_1 + FinalSum1_2;

  assign Bit_Slice6_out1 = Delay19_out1_1[3:0];

  assign Bit_Concat1_out1_2 = {FinalSum1_out1, Bit_Slice6_out1};

  assign Data_Type_Conversion_out1 = Bit_Concat1_out1_2[47:0];

  assign Constant1_out1_2 = 1'b0;

  assign Bit_Concat_out1_1 = {Data_Type_Conversion_out1, Constant1_out1_2};

  always @(posedge clk or posedge reset)
    begin : Delay3_4_process
      if (reset == 1'b1) begin
        Delay3_out1_4 <= 49'h0000000000000;
      end
      else begin
        if (enb) begin
          Delay3_out1_4 <= Bit_Concat_out1_1;
        end
      end
    end

  assign Bit_Slice1_out1_2 = Delay3_out1_4[48];

  assign Logical_Operator1_out1_1 = Delay21_out1 | Delay16_out1;

  always @(posedge clk or posedge reset)
    begin : Delay3_5_process
      if (reset == 1'b1) begin
        Delay3_out1_5 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay3_out1_5 <= Logical_Operator1_out1_1;
        end
      end
    end

  assign Logical_Operator3_out1_1 =  ~ Delay3_out1_5;

  assign Logical_Operator_out1_4 = Delay23_out1 | Delay20_out1;

  always @(posedge clk or posedge reset)
    begin : Delay1_process
      if (reset == 1'b1) begin
        Delay1_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay1_out1 <= Logical_Operator_out1_4;
        end
      end
    end

  assign Logical_Operator2_out1_1 = Logical_Operator3_out1_1 & Delay1_out1;

  always @(posedge clk or posedge reset)
    begin : Delay8_2_process
      if (reset == 1'b1) begin
        Delay8_reg_1 <= {4{1'b0}};
      end
      else begin
        if (enb) begin
          Delay8_reg_1[0] <= Logical_Operator2_out1_1;
          Delay8_reg_1[32'sd3:32'sd1] <= Delay8_reg_1[32'sd2:32'sd0];
        end
      end
    end

  assign Delay8_out1_2 = Delay8_reg_1[3];

  always @(posedge clk or posedge reset)
    begin : Delay4_2_process
      if (reset == 1'b1) begin
        Delay4_out1_2 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          Delay4_out1_2 <= AE;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay5_1_process
      if (reset == 1'b1) begin
        Delay5_out1_1 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          Delay5_out1_1 <= BE;
        end
      end
    end

  assign Subtract_1 = {24'b0, Delay4_out1_2};
  assign Subtract_2 = {24'b0, Delay5_out1_1};
  assign Subtract_add_temp = Subtract_1 + Subtract_2;
  assign Subtract_out1 = Subtract_add_temp[8:0];

  always @(posedge clk or posedge reset)
    begin : Delay_1_process
      if (reset == 1'b1) begin
        Delay_out1_1 <= 9'b000000000;
      end
      else begin
        if (enb) begin
          Delay_out1_1 <= Subtract_out1;
        end
      end
    end

  assign Constant2_out1_1 = 7'b0111111;

  assign Constant1_out1_3 = 1'b1;

  assign Constant3_out1_1 = 1'b0;

  assign Switch_out1_2 = (Delay23_out1 == 1'b0 ? Constant1_out1_3 :
              Constant3_out1_1);

  assign Bit_Concat1_out1_3 = {Constant2_out1_1, Switch_out1_2};

  assign Switch1_out1_2 = (Delay20_out1 == 1'b0 ? Constant1_out1_3 :
              Constant3_out1_1);

  assign Bit_Concat_out1_2 = {Constant2_out1_1, Switch1_out1_2};

  assign Add1_1 = {24'b0, Bit_Concat1_out1_3};
  assign Add1_2 = {24'b0, Bit_Concat_out1_2};
  assign Add1_add_temp = Add1_1 + Add1_2;
  assign Add1_out1 = Add1_add_temp[8:0];

  always @(posedge clk or posedge reset)
    begin : Delay2_1_process
      if (reset == 1'b1) begin
        Delay2_out1_1 <= 9'b000000000;
      end
      else begin
        if (enb) begin
          Delay2_out1_1 <= Add1_out1;
        end
      end
    end

  assign Subtract2_1 = {23'b0, Delay_out1_1};
  assign Subtract2_2 = {23'b0, Delay2_out1_1};
  assign Subtract2_sub_temp = Subtract2_1 - Subtract2_2;
  assign Subtract2_out1 = Subtract2_sub_temp[9:0];

  assign Constant4_out1_1 = 10'sb0011111111;

  assign Switch2_out1_1 = (Delay3_out1_5 == 1'b0 ? Subtract2_out1 :
              Constant4_out1_1);

  always @(posedge clk or posedge reset)
    begin : Delay4_3_process
      if (reset == 1'b1) begin
        for(Delay4_t_1 = 32'sd0; Delay4_t_1 <= 32'sd3; Delay4_t_1 = Delay4_t_1 + 32'sd1) begin
          Delay4_reg[Delay4_t_1] <= 10'sb0000000000;
        end
      end
      else begin
        if (enb) begin
          for(Delay4_t_0_1 = 32'sd0; Delay4_t_0_1 <= 32'sd3; Delay4_t_0_1 = Delay4_t_0_1 + 32'sd1) begin
            Delay4_reg[Delay4_t_0_1] <= Delay4_reg_next[Delay4_t_0_1];
          end
        end
      end
    end

  always @* begin
    Delay4_out1_3 = Delay4_reg[3];
    Delay4_reg_next[0] = Switch2_out1_1;

    for(Delay4_t_0_0 = 32'sd0; Delay4_t_0_0 <= 32'sd2; Delay4_t_0_0 = Delay4_t_0_0 + 32'sd1) begin
      Delay4_reg_next[Delay4_t_0_0 + 32'sd1] = Delay4_reg[Delay4_t_0_0];
    end

  end

  assign Constant_out1_1 = 10'sb1000000001;

  assign Switch1_out1_3 = (Delay8_out1_2 == 1'b0 ? Delay4_out1_3 :
              Constant_out1_1);

  assign Add_3 = {31'b0, Bit_Slice1_out1_2};
  assign Add_4 = {{22{Switch1_out1_3[9]}}, Switch1_out1_3};
  assign Add_add_temp = Add_3 + Add_4;
  assign Add_out1_1 = Add_add_temp[9:0];

  assign Compare_To_Constant_out1_1 = Add_out1_1 > 10'sb1110000001;

  assign Constant1_out1_4 = 10'sb1110000000;

  assign Switch2_out1_2 = (Compare_To_Constant_out1_1 == 1'b0 ? Constant1_out1_4 :
              Add_out1_1);

  always @(posedge clk or posedge reset)
    begin : Delay18_process
      if (reset == 1'b1) begin
        Delay18_out1 <= 10'sb0000000000;
      end
      else begin
        if (enb) begin
          Delay18_out1 <= Switch2_out1_2;
        end
      end
    end

  assign Compare_To_Constant1_out1_1 = Delay18_out1 > 10'sb0001111111;

  assign Logical_Operator1_out1_2 =  ~ Delay14_out1;

  assign Logical_Operator4_out1 = Logical_Operator1_out1_2 & Delay20_out1;

  assign Logical_Operator7_out1 = Logical_Operator4_out1 & Delay21_out1;

  assign Logical_Operator5_out1 =  ~ Delay19_out1;

  assign Logical_Operator6_out1 = Logical_Operator5_out1 & Delay23_out1;

  assign Logical_Operator8_out1 = Logical_Operator6_out1 & Delay16_out1;

  assign Inf_Zero_out1 = Logical_Operator7_out1 | Logical_Operator8_out1;

  assign Logical_Operator2_out1_2 = Logical_Operator_out1 | Logical_Operator1_out1;

  assign Logical_Operator10_out1 = Inf_Zero_out1 | Logical_Operator2_out1_2;

  always @(posedge clk or posedge reset)
    begin : Delay13_1_process
      if (reset == 1'b1) begin
        Delay13_reg <= {6{1'b0}};
      end
      else begin
        if (enb) begin
          Delay13_reg[0] <= Logical_Operator10_out1;
          Delay13_reg[32'sd5:32'sd1] <= Delay13_reg[32'sd4:32'sd0];
        end
      end
    end

  assign Delay13_out1_1 = Delay13_reg[5];

  assign Logical_Operator_out1_5 = Compare_To_Constant1_out1_1 | Delay13_out1_1;

  assign Compare_To_Constant_out1_2 = Delay18_out1 < 10'sb1110000001;

  assign Constant1_out1_5 = 8'b01111111;

  assign Bit_Shift_out1 = Delay3_out1_4 >> 8'd1;

  assign Switch_out1_3 = (Bit_Slice1_out1_2 == 1'b0 ? Delay3_out1_4 :
              Bit_Shift_out1);

  assign Bit_Slice_out1_1 = Switch_out1_3[47:0];

  assign Bit_Slice2_out1_1 = Bit_Slice_out1_1[23:22];

  assign Bit_Slice4_out1_1 = Bit_Slice2_out1_1[0];

  assign Bit_Slice1_out1_3 = Bit_Slice_out1_1[21:0];

  assign Bit_Reduce_out1 = (|Bit_Slice1_out1_3[21:0]);

  assign Bit_Slice5_out1_1 = Bit_Slice2_out1_1[1];

  assign Bit_Slice3_out1_1 = Bit_Slice_out1_1[24];

  assign Logical_Operator1_out1_3 = Bit_Slice3_out1_1 | (Bit_Slice4_out1_1 | Bit_Reduce_out1);

  assign Logical_Operator_out1_6 = Bit_Slice5_out1_1 & Logical_Operator1_out1_3;

  assign Bit_Slice1_out1_4 = Bit_Slice_out1_1[46:24];

  always @(posedge clk or posedge reset)
    begin : Delay1_1_process
      if (reset == 1'b1) begin
        Delay1_out1_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay1_out1_1 <= Logical_Operator_out1_6;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay2_2_process
      if (reset == 1'b1) begin
        Delay2_out1_2 <= 23'b00000000000000000000000;
      end
      else begin
        if (enb) begin
          Delay2_out1_2 <= Bit_Slice1_out1_4;
        end
      end
    end

  assign Delay2_out1_dtc = {1'b0, Delay2_out1_2};

  assign Constant_out1_2 = 1'b1;

  assign Add_6 = {9'b0, Bit_Slice1_out1_4};
  assign Add_7 = {31'b0, Constant_out1_2};
  assign Add_add_temp_1 = Add_6 + Add_7;
  assign Add_out1_2 = Add_add_temp_1[23:0];

  always @(posedge clk or posedge reset)
    begin : Delay_2_process
      if (reset == 1'b1) begin
        Delay_out1_2 <= 24'b000000000000000000000000;
      end
      else begin
        if (enb) begin
          Delay_out1_2 <= Add_out1_2;
        end
      end
    end

  assign Switch_out1_4 = (Delay1_out1_1 == 1'b0 ? Delay2_out1_dtc :
              Delay_out1_2);

  assign Bit_Slice2_out1_2 = Switch_out1_4[23];

  assign Add1_4 = {24'b0, Constant1_out1_5};
  assign Add1_5 = {31'b0, Bit_Slice2_out1_2};
  assign Add1_add_temp_1 = Add1_4 + Add1_5;
  assign Add1_out1_1 = Add1_add_temp_1[7:0];

  assign Add_9 = {24'b0, Add1_out1_1};
  assign Add_10 = {{22{Delay18_out1[9]}}, Delay18_out1};
  assign Add_add_temp_2 = Add_9 + Add_10;
  assign Add_out1_3 = Add_add_temp_2[7:0];

  assign Constant1_out1_6 = 8'b00000000;

  assign Switch1_out1_4 = (Compare_To_Constant_out1_2 == 1'b0 ? Add_out1_3 :
              Constant1_out1_6);

  assign Constant4_out1_2 = 8'b11111111;

  assign Switch4_out1 = (Logical_Operator_out1_5 == 1'b0 ? Switch1_out1_4 :
              Constant4_out1_2);

  assign Switch6_out1 = (Relational_Operator_out1 == 1'b0 ? Constant6_out1 :
              Switch4_out1);

  always @(posedge clk or posedge reset)
    begin : Delay1_2_process
      if (reset == 1'b1) begin
        Delay1_out1_2 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          Delay1_out1_2 <= Switch6_out1;
        end
      end
    end

  assign Bit_Slice4_out1_2 = Switch_out1_4[22:0];

  assign Bit_Shift_out1_1 = Bit_Slice4_out1_2 >> 8'd1;

  assign Switch1_out1_5 = (Bit_Slice2_out1_2 == 1'b0 ? Bit_Slice4_out1_2 :
              Bit_Shift_out1_1);

  assign Constant2_out1_2 = 23'b00000000000000000000000;

  assign Switch2_out1_3 = (Compare_To_Constant_out1_2 == 1'b0 ? Switch1_out1_5 :
              Constant2_out1_2);

  assign Constant5_out1_1 = 23'b00000000000000000000000;

  assign Bit_Set_out1 = Switch2_out1_3 | 23'b10000000000000000000000;

  assign Switch7_out1 = (Delay13_out1_1 == 1'b0 ? Constant5_out1_1 :
              Bit_Set_out1);

  assign Switch5_out1 = (Logical_Operator_out1_5 == 1'b0 ? Switch2_out1_3 :
              Switch7_out1);

  always @(posedge clk or posedge reset)
    begin : Delay2_3_process
      if (reset == 1'b1) begin
        Delay2_out1_3 <= 23'b00000000000000000000000;
      end
      else begin
        if (enb) begin
          Delay2_out1_3 <= Switch5_out1;
        end
      end
    end

  // Combine FP sign, exponent, mantissa into 32 bit word
  assign nfp_out_pack = {Delay_out1, Delay1_out1_2, Delay2_out1_3};

  assign nfp_out = nfp_out_pack;

endmodule  // nfp_mul_single

