// -------------------------------------------------------------
// 
// File Name: hdlsrc/MAC/nfp_mul_single.v
// Created: 2026-09-05 13:50:56
// 
// Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: nfp_mul_single
// Source Path: MAC/FP16/nfp_mul_single
// Hierarchy Level: 1
// Model version: 1.3
// 
// {Latency Strategy = "Min", Denormal Handling = "on"}
// {Mantissa Multiply Strategy = "FullMultiplier"}
// 
// -------------------------------------------------------------


/* verilator lint_off WIDTHEXPAND */
/* verilator lint_off UNUSEDSIGNAL */
module nfp_mul_single
          (clk,
           reset,
           enb,
           nfp_in1,
           nfp_in2,
           nfp_out);


  input   clk;
  input   reset;
  input   enb;
  input   [31:0] nfp_in1;  // ufix32
  input   [31:0] nfp_in2;  // ufix32
  output  [31:0] nfp_out;  // ufix32


  wire BS;  // ufix1
  wire [7:0] BE;  // ufix8
  wire [22:0] BM;  // ufix23
  wire Compare_To_Constant1_out1;
  reg  Delay16_out1;
  wire Compare_To_Zero3_out1;
  reg  Delay14_out1;
  wire Logical_Operator1_out1;
  wire AS;  // ufix1
  wire [7:0] AE;  // ufix8
  wire [22:0] AM;  // ufix23
  wire Compare_To_Constant_out1;
  reg  Delay21_out1;
  wire Compare_To_Zero2_out1;
  reg  Delay19_out1;
  wire Logical_Operator_out1;
  reg  Delay3_out1;
  reg  Delay7_out1;
  wire Logical_Operator_out1_1;
  wire Switch_out1;
  wire Switch1_out1;
  reg  [2:0] Delay29_reg;  // ufix1 [3]
  wire Delay29_out1;
  reg  [1:0] Delay_reg;  // ufix1 [2]
  wire Delay_out1;
  wire Constant8_out1;  // ufix1
  wire [7:0] Constant7_out1;  // uint8
  wire Relational_Operator_out1;
  reg  Delay4_out1;
  wire Logical_Operator2_out1;
  wire Logical_Operator_out1_2;  // ufix1
  wire [7:0] Add_out1;  // uint8
  reg [7:0] Delay3_out1_1;  // uint8
  wire [7:0] Add_1;  // ufix8
  wire [7:0] Constant6_out1;  // uint8
  wire Compare_To_Zero_out1;
  reg  Delay23_out1;
  wire Constant1_out1;  // ufix1
  wire Constant_out1;  // ufix1
  wire Switch1_out1_1;  // ufix1
  reg [22:0] Delay6_out1;  // ufix23
  wire [23:0] Bit_Concat_out1;  // ufix24
  wire [23:0] Constant5_out1;  // ufix24
  wire [23:0] Switch_out1_1;  // ufix24
  reg [23:0] Delay2_out1;  // ufix24
  wire Logical_Operator3_out1;
  wire Compare_To_Zero1_out1;
  reg  Delay20_out1;
  wire Constant3_out1;  // ufix1
  wire Constant2_out1;  // ufix1
  wire Switch2_out1;  // ufix1
  wire Logical_Operator_out1_3;
  reg [22:0] Delay8_out1;  // ufix23
  wire [23:0] Bit_Concat1_out1;  // ufix24
  wire [23:0] Constant4_out1;  // ufix24
  wire [23:0] Switch3_out1;  // ufix24
  reg [23:0] Delay1_out1;  // ufix24
  wire [47:0] Product_out1;  // ufix48
  reg [47:0] Delay4_out1_1;  // ufix48
  wire Constant1_out1_1;
  wire [48:0] Bit_Concat_out1_1;  // ufix49
  wire Compare_To_Zero1_out1_1;
  wire Logical_Operator1_out1_1;
  reg [7:0] Delay4_out1_2;  // uint8
  reg [7:0] Delay5_out1;  // uint8
  wire [31:0] Subtract_add_temp;  // ufix32
  wire [31:0] Subtract_1;  // ufix32
  wire [31:0] Subtract_2;  // ufix32
  wire [8:0] Subtract_out1;  // ufix9
  reg [8:0] Delay_out1_1;  // ufix9
  wire [6:0] Constant2_out1_1;  // ufix7
  wire Constant1_out1_2;
  wire Constant3_out1_1;
  wire Switch_out1_2;
  wire [7:0] Bit_Concat1_out1_1;  // uint8
  wire Switch1_out1_2;
  wire [7:0] Bit_Concat_out1_2;  // uint8
  wire [31:0] Add1_add_temp;  // ufix32
  wire [31:0] Add1_1;  // ufix32
  wire [31:0] Add1_2;  // ufix32
  wire [8:0] Add1_out1;  // ufix9
  reg  Delay3_out1_2;
  reg [8:0] Delay2_out1_1;  // ufix9
  wire signed [31:0] Subtract2_sub_temp;  // sfix32
  wire signed [31:0] Subtract2_1;  // sfix32
  wire signed [31:0] Subtract2_2;  // sfix32
  wire signed [9:0] Subtract2_out1;  // sfix10
  wire signed [9:0] Constant4_out1_1;  // sfix10
  wire signed [9:0] Switch2_out1_1;  // sfix10
  reg signed [9:0] Delay27_out1;  // sfix10
  wire signed [9:0] Constant_out1_1;  // sfix10
  wire signed [9:0] Switch1_out1_3;  // sfix10
  reg signed [9:0] Delay5_out1_1;  // sfix10
  wire Bit_Slice25_out1;  // ufix1
  wire signed [5:0] Constant25_out1;  // sfix6
  wire Bit_Slice24_out1;  // ufix1
  wire signed [5:0] Constant24_out1;  // sfix6
  wire signed [5:0] Switch24_out1;  // sfix6
  wire Bit_Slice23_out1;  // ufix1
  wire signed [5:0] Constant23_out1;  // sfix6
  wire signed [5:0] Switch23_out1;  // sfix6
  wire Bit_Slice22_out1;  // ufix1
  wire signed [5:0] Constant22_out1;  // sfix6
  wire signed [5:0] Switch22_out1;  // sfix6
  wire Bit_Slice21_out1;  // ufix1
  wire signed [5:0] Constant21_out1;  // sfix6
  wire signed [5:0] Switch21_out1;  // sfix6
  wire Bit_Slice10_out1;  // ufix1
  wire signed [5:0] Constant20_out1;  // sfix6
  wire signed [5:0] Switch20_out1;  // sfix6
  wire Bit_Slice19_out1;  // ufix1
  wire signed [5:0] Constant19_out1;  // sfix6
  wire signed [5:0] Switch19_out1;  // sfix6
  wire Bit_Slice18_out1;  // ufix1
  wire signed [5:0] Constant18_out1;  // sfix6
  wire signed [5:0] Switch18_out1;  // sfix6
  wire Bit_Slice17_out1;  // ufix1
  wire signed [5:0] Constant17_out1;  // sfix6
  wire signed [5:0] Switch17_out1;  // sfix6
  wire Bit_Slice16_out1;  // ufix1
  wire signed [5:0] Constant16_out1;  // sfix6
  wire signed [5:0] Switch16_out1;  // sfix6
  wire Bit_Slice15_out1;  // ufix1
  wire signed [5:0] Constant15_out1;  // sfix6
  wire signed [5:0] Switch15_out1;  // sfix6
  wire Bit_Slice14_out1;  // ufix1
  wire signed [5:0] Constant14_out1;  // sfix6
  wire signed [5:0] Switch14_out1;  // sfix6
  wire Bit_Slice13_out1;  // ufix1
  wire signed [5:0] Constant13_out1;  // sfix6
  wire signed [5:0] Switch13_out1;  // sfix6
  wire Bit_Slice12_out1;  // ufix1
  wire signed [5:0] Constant12_out1;  // sfix6
  wire signed [5:0] Switch12_out1;  // sfix6
  wire Bit_Slice11_out1;  // ufix1
  wire signed [5:0] Constant11_out1;  // sfix6
  wire signed [5:0] Switch11_out1;  // sfix6
  wire Bit_Slice_out1;  // ufix1
  wire signed [5:0] Constant10_out1;  // sfix6
  wire signed [5:0] Switch10_out1;  // sfix6
  wire Bit_Slice9_out1;  // ufix1
  wire signed [5:0] Constant9_out1;  // sfix6
  wire signed [5:0] Switch9_out1;  // sfix6
  wire Bit_Slice8_out1;  // ufix1
  wire signed [5:0] Constant8_out1_1;  // sfix6
  wire signed [5:0] Switch8_out1;  // sfix6
  wire Bit_Slice7_out1;  // ufix1
  wire signed [5:0] Constant7_out1_1;  // sfix6
  wire signed [5:0] Switch7_out1;  // sfix6
  wire Bit_Slice6_out1;  // ufix1
  wire signed [5:0] Constant6_out1_1;  // sfix6
  wire signed [5:0] Switch6_out1;  // sfix6
  wire Bit_Slice5_out1;  // ufix1
  wire signed [5:0] Constant5_out1_1;  // sfix6
  wire signed [5:0] Switch5_out1;  // sfix6
  wire Bit_Slice4_out1;  // ufix1
  wire signed [5:0] Constant4_out1_2;  // sfix6
  wire signed [5:0] Switch4_out1;  // sfix6
  wire Bit_Slice3_out1;  // ufix1
  wire signed [5:0] Constant3_out1_2;  // sfix6
  wire signed [5:0] Switch3_out1_1;  // sfix6
  wire Bit_Slice2_out1;  // ufix1
  wire signed [5:0] Constant2_out1_2;  // sfix6
  wire signed [5:0] Switch2_out1_2;  // sfix6
  wire Bit_Slice1_out1;  // ufix1
  wire signed [5:0] Constant1_out1_3;  // sfix6
  wire signed [5:0] Switch1_out1_4;  // sfix6
  wire signed [5:0] Constant26_out1;  // sfix6
  wire signed [5:0] Switch_out1_3;  // sfix6
  reg signed [5:0] Delay1_out1_1;  // sfix6
  wire signed [31:0] Add_sub_temp;  // sfix32
  wire signed [31:0] Add_3;  // sfix32
  wire signed [31:0] Add_4;  // sfix32
  wire signed [9:0] Add_out1_1;  // sfix10
  wire Compare_To_Constant_out1_1;
  wire signed [8:0] Constant1_out1_4;  // sfix9
  wire signed [9:0] Constant1_out1_dtc;  // sfix10
  wire signed [9:0] Switch_out1_4;  // sfix10
  reg signed [9:0] Delay18_out1;  // sfix10
  wire Compare_To_Constant1_out1_1;
  wire Logical_Operator1_out1_2;
  wire Logical_Operator4_out1;
  wire Logical_Operator7_out1;
  wire Logical_Operator5_out1;
  wire Logical_Operator6_out1;
  wire Logical_Operator8_out1;
  wire Inf_Zero_out1;
  wire Logical_Operator2_out1_1;
  wire Logical_Operator10_out1;
  reg  [2:0] Delay22_reg;  // ufix1 [3]
  wire Delay22_out1;
  reg  Delay13_out1;
  wire Logical_Operator_out1_4;
  wire Compare_To_Constant_out1_2;
  wire [7:0] Constant1_out1_5;  // uint8
  reg [48:0] Delay2_out1_2;  // ufix49
  wire Compare_To_Zero_out1_1;
  wire [4:0] Bit_Slice_out1_1;  // ufix5
  wire [7:0] dynamic_shift_1;  // uint8
  wire [48:0] Shift_Arithmetic_out1;  // ufix49
  wire [48:0] Bit_Shift_out1;  // ufix49
  reg [48:0] Delay3_out1_3;  // ufix49
  wire [48:0] Switch_out1_5;  // ufix49
  wire signed [8:0] Constant_out1_2;  // sfix9
  wire signed [31:0] Subtract_sub_temp;  // sfix32
  wire signed [31:0] Subtract_4;  // sfix32
  wire signed [31:0] Subtract_5;  // sfix32
  wire signed [15:0] Subtract_out1_1;  // int16
  wire Compare_To_Constant_out1_3;
  wire signed [5:0] Subtract_out1_dtc;  // sfix6
  wire Compare_To_Constant1_out1_2;
  wire signed [5:0] Constant1_out1_6;  // sfix6
  wire signed [5:0] Switch_out1_6;  // sfix6
  wire signed [5:0] Constant2_out1_3;  // sfix6
  wire signed [5:0] Switch1_out1_5;  // sfix6
  wire signed [6:0] Unary_Minus_in0;  // sfix7
  wire signed [6:0] Unary_Minus_1;  // sfix7
  wire signed [5:0] Unary_Minus_out1;  // sfix6
  wire shift_arithmetic_shift_direction;
  wire [30:0] Constant_out1_3;  // ufix31
  wire [79:0] Bit_Concat_out1_3;  // ufix80
  wire signed [6:0] shift_arithmetic_abs_y;  // sfix7
  wire signed [6:0] shift_arithmetic_abs_1;  // sfix7
  wire [6:0] shift_arithmetic_shift_value;  // ufix7
  wire [7:0] shift_right_1;  // uint8
  wire [79:0] shift_arithmetic_right;  // ufix80
  wire [7:0] shift_left_1;  // uint8
  wire [79:0] shift_arithmetic_left;  // ufix80
  wire [79:0] Shift_Arithmetic_out1_1;  // ufix80
  wire [30:0] Bit_Slice1_out1_1;  // ufix31
  wire switch_compare_1;
  wire [48:0] Bit_Slice_out1_2;  // ufix49
  wire [48:0] Bit_Set_out1;  // ufix49
  wire [48:0] Switch2_out1_3;  // ufix49
  wire [48:0] Switch1_out1_6;  // ufix49
  wire [47:0] Bit_Slice_out1_3;  // ufix48
  wire [1:0] Bit_Slice2_out1_1;  // ufix2
  wire Bit_Slice4_out1_1;  // ufix1
  wire [21:0] Bit_Slice1_out1_2;  // ufix22
  wire Bit_Reduce_out1;  // ufix1
  wire Bit_Slice5_out1_1;  // ufix1
  wire Bit_Slice3_out1_1;  // ufix1
  wire Logical_Operator1_out1_3;
  wire Logical_Operator_out1_5;
  reg  Delay1_out1_2;
  wire [22:0] Bit_Slice1_out1_3;  // ufix23
  reg [22:0] Bit_Slice1_out1_4;  // ufix23
  wire [23:0] Bit_Slice1_out1_dtc;  // ufix24
  wire Constant_out1_4;
  wire [31:0] Add_add_temp;  // ufix32
  wire [31:0] Add_6;  // ufix32
  wire [31:0] Add_7;  // ufix32
  wire [23:0] Add_out1_2;  // ufix24
  wire [23:0] Switch_out1_7;  // ufix24
  wire Bit_Slice2_out1_2;  // ufix1
  wire [31:0] Add1_add_temp_1;  // ufix32
  wire [31:0] Add1_4;  // ufix32
  wire [31:0] Add1_5;  // ufix32
  wire [7:0] Add1_out1_1;  // uint8
  wire signed [31:0] Add_add_temp_1;  // sfix32
  wire signed [31:0] Add_9;  // sfix32
  wire signed [31:0] Add_10;  // sfix32
  wire [7:0] Add_out1_3;  // uint8
  wire [7:0] Constant1_out1_7;  // uint8
  wire [7:0] Switch1_out1_7;  // uint8
  wire [7:0] Constant4_out1_3;  // uint8
  wire [7:0] Switch4_out1_1;  // uint8
  wire [7:0] Switch6_out1_1;  // uint8
  reg [7:0] Delay1_out1_3;  // uint8
  wire [22:0] Bit_Slice4_out1_2;  // ufix23
  wire [22:0] Bit_Shift_out1_1;  // ufix23
  wire [22:0] Switch1_out1_8;  // ufix23
  wire [22:0] Constant2_out1_4;  // ufix23
  wire [22:0] Switch2_out1_4;  // ufix23
  wire [22:0] Constant5_out1_2;  // ufix23
  wire [22:0] Bit_Set_out1_1;  // ufix23
  wire [22:0] Switch7_out1_1;  // ufix23
  wire [22:0] Switch5_out1_1;  // ufix23
  reg [22:0] Delay2_out1_3;  // ufix23
  wire [31:0] nfp_out_pack;  // ufix32


  // Split 32 bit word into FP sign, exponent, mantissa
  assign BS = nfp_in2[31];
  assign BE = nfp_in2[30:23];
  assign BM = nfp_in2[22:0];

  assign Compare_To_Constant1_out1 = BE == 8'b11111111;

  always @(posedge clk or posedge reset)
    begin : Delay16_process
      if (reset == 1'b1) begin
        Delay16_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay16_out1 <= Compare_To_Constant1_out1;
        end
      end
    end

  assign Compare_To_Zero3_out1 = BM != 23'b00000000000000000000000;

  always @(posedge clk or posedge reset)
    begin : Delay14_process
      if (reset == 1'b1) begin
        Delay14_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay14_out1 <= Compare_To_Zero3_out1;
        end
      end
    end

  assign Logical_Operator1_out1 = Delay16_out1 & Delay14_out1;

  // Split 32 bit word into FP sign, exponent, mantissa
  assign AS = nfp_in1[31];
  assign AE = nfp_in1[30:23];
  assign AM = nfp_in1[22:0];

  assign Compare_To_Constant_out1 = AE == 8'b11111111;

  always @(posedge clk or posedge reset)
    begin : Delay21_process
      if (reset == 1'b1) begin
        Delay21_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay21_out1 <= Compare_To_Constant_out1;
        end
      end
    end

  assign Compare_To_Zero2_out1 = AM != 23'b00000000000000000000000;

  always @(posedge clk or posedge reset)
    begin : Delay19_process
      if (reset == 1'b1) begin
        Delay19_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay19_out1 <= Compare_To_Zero2_out1;
        end
      end
    end

  assign Logical_Operator_out1 = Delay21_out1 & Delay19_out1;

  always @(posedge clk or posedge reset)
    begin : Delay3_process
      if (reset == 1'b1) begin
        Delay3_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay3_out1 <= AS;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay7_process
      if (reset == 1'b1) begin
        Delay7_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay7_out1 <= BS;
        end
      end
    end

  assign Logical_Operator_out1_1 = Delay3_out1 ^ Delay7_out1;

  assign Switch_out1 = (Logical_Operator_out1 == 1'b0 ? Logical_Operator_out1_1 :
              Delay3_out1);

  assign Switch1_out1 = (Logical_Operator1_out1 == 1'b0 ? Switch_out1 :
              Delay7_out1);

  always @(posedge clk or posedge reset)
    begin : Delay29_process
      if (reset == 1'b1) begin
        Delay29_reg <= {3{1'b0}};
      end
      else begin
        if (enb) begin
          Delay29_reg[0] <= Switch1_out1;
          Delay29_reg[32'sd2:32'sd1] <= Delay29_reg[32'sd1:32'sd0];
        end
      end
    end

  assign Delay29_out1 = Delay29_reg[2];

  always @(posedge clk or posedge reset)
    begin : Delay_process
      if (reset == 1'b1) begin
        Delay_reg <= {2{1'b0}};
      end
      else begin
        if (enb) begin
          Delay_reg[0] <= Delay29_out1;
          Delay_reg[1] <= Delay_reg[0];
        end
      end
    end

  assign Delay_out1 = Delay_reg[1];

  assign Constant8_out1 = 1'b1;

  assign Constant7_out1 = 8'b00000110;

  always @(posedge clk or posedge reset)
    begin : Delay4_process
      if (reset == 1'b1) begin
        Delay4_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay4_out1 <= Relational_Operator_out1;
        end
      end
    end

  assign Logical_Operator2_out1 =  ~ Delay4_out1;

  assign Logical_Operator_out1_2 = Constant8_out1 & Logical_Operator2_out1;

  always @(posedge clk or posedge reset)
    begin : Delay3_1_process
      if (reset == 1'b1) begin
        Delay3_out1_1 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          Delay3_out1_1 <= Add_out1;
        end
      end
    end

  assign Add_1 = {7'b0, Logical_Operator_out1_2};
  assign Add_out1 = Delay3_out1_1 + Add_1;

  assign Relational_Operator_out1 = Add_out1 >= Constant7_out1;

  assign Constant6_out1 = 8'b00000000;

  assign Compare_To_Zero_out1 = AE == 8'b00000000;

  always @(posedge clk or posedge reset)
    begin : Delay23_process
      if (reset == 1'b1) begin
        Delay23_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay23_out1 <= Compare_To_Zero_out1;
        end
      end
    end

  assign Constant1_out1 = 1'b1;

  assign Constant_out1 = 1'b0;

  assign Switch1_out1_1 = (Delay23_out1 == 1'b0 ? Constant1_out1 :
              Constant_out1);

  always @(posedge clk or posedge reset)
    begin : Delay6_process
      if (reset == 1'b1) begin
        Delay6_out1 <= 23'b00000000000000000000000;
      end
      else begin
        if (enb) begin
          Delay6_out1 <= AM;
        end
      end
    end

  assign Bit_Concat_out1 = {Switch1_out1_1, Delay6_out1};

  assign Constant5_out1 = 24'b100000000000000000000000;

  assign Switch_out1_1 = (Logical_Operator1_out1 == 1'b0 ? Bit_Concat_out1 :
              Constant5_out1);

  always @(posedge clk or posedge reset)
    begin : Delay2_process
      if (reset == 1'b1) begin
        Delay2_out1 <= 24'b000000000000000000000000;
      end
      else begin
        if (enb) begin
          Delay2_out1 <= Switch_out1_1;
        end
      end
    end

  assign Logical_Operator3_out1 =  ~ Logical_Operator1_out1;

  assign Compare_To_Zero1_out1 = BE == 8'b00000000;

  always @(posedge clk or posedge reset)
    begin : Delay20_process
      if (reset == 1'b1) begin
        Delay20_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay20_out1 <= Compare_To_Zero1_out1;
        end
      end
    end

  assign Constant3_out1 = 1'b1;

  assign Constant2_out1 = 1'b0;

  assign Switch2_out1 = (Delay20_out1 == 1'b0 ? Constant3_out1 :
              Constant2_out1);

  assign Logical_Operator_out1_3 = Logical_Operator_out1 & Logical_Operator3_out1;

  always @(posedge clk or posedge reset)
    begin : Delay8_process
      if (reset == 1'b1) begin
        Delay8_out1 <= 23'b00000000000000000000000;
      end
      else begin
        if (enb) begin
          Delay8_out1 <= BM;
        end
      end
    end

  assign Bit_Concat1_out1 = {Switch2_out1, Delay8_out1};

  assign Constant4_out1 = 24'b100000000000000000000000;

  assign Switch3_out1 = (Logical_Operator_out1_3 == 1'b0 ? Bit_Concat1_out1 :
              Constant4_out1);

  always @(posedge clk or posedge reset)
    begin : Delay1_process
      if (reset == 1'b1) begin
        Delay1_out1 <= 24'b000000000000000000000000;
      end
      else begin
        if (enb) begin
          Delay1_out1 <= Switch3_out1;
        end
      end
    end

  assign Product_out1 = Delay2_out1 * Delay1_out1;

  always @(posedge clk or posedge reset)
    begin : Delay4_1_process
      if (reset == 1'b1) begin
        Delay4_out1_1 <= 48'h000000000000;
      end
      else begin
        if (enb) begin
          Delay4_out1_1 <= Product_out1;
        end
      end
    end

  assign Constant1_out1_1 = 1'b0;

  assign Bit_Concat_out1_1 = {Delay4_out1_1, Constant1_out1_1};

  assign Compare_To_Zero1_out1_1 = Bit_Concat_out1_1 == 49'h0000000000000;

  assign Logical_Operator1_out1_1 = Delay21_out1 | Delay16_out1;

  always @(posedge clk or posedge reset)
    begin : Delay4_2_process
      if (reset == 1'b1) begin
        Delay4_out1_2 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          Delay4_out1_2 <= AE;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay5_process
      if (reset == 1'b1) begin
        Delay5_out1 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          Delay5_out1 <= BE;
        end
      end
    end

  assign Subtract_1 = {24'b0, Delay4_out1_2};
  assign Subtract_2 = {24'b0, Delay5_out1};
  assign Subtract_add_temp = Subtract_1 + Subtract_2;
  assign Subtract_out1 = Subtract_add_temp[8:0];

  always @(posedge clk or posedge reset)
    begin : Delay_1_process
      if (reset == 1'b1) begin
        Delay_out1_1 <= 9'b000000000;
      end
      else begin
        if (enb) begin
          Delay_out1_1 <= Subtract_out1;
        end
      end
    end

  assign Constant2_out1_1 = 7'b0111111;

  assign Constant1_out1_2 = 1'b1;

  assign Constant3_out1_1 = 1'b0;

  assign Switch_out1_2 = (Delay23_out1 == 1'b0 ? Constant1_out1_2 :
              Constant3_out1_1);

  assign Bit_Concat1_out1_1 = {Constant2_out1_1, Switch_out1_2};

  assign Switch1_out1_2 = (Delay20_out1 == 1'b0 ? Constant1_out1_2 :
              Constant3_out1_1);

  assign Bit_Concat_out1_2 = {Constant2_out1_1, Switch1_out1_2};

  assign Add1_1 = {24'b0, Bit_Concat1_out1_1};
  assign Add1_2 = {24'b0, Bit_Concat_out1_2};
  assign Add1_add_temp = Add1_1 + Add1_2;
  assign Add1_out1 = Add1_add_temp[8:0];

  always @(posedge clk or posedge reset)
    begin : Delay3_2_process
      if (reset == 1'b1) begin
        Delay3_out1_2 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay3_out1_2 <= Logical_Operator1_out1_1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : Delay2_1_process
      if (reset == 1'b1) begin
        Delay2_out1_1 <= 9'b000000000;
      end
      else begin
        if (enb) begin
          Delay2_out1_1 <= Add1_out1;
        end
      end
    end

  assign Subtract2_1 = {23'b0, Delay_out1_1};
  assign Subtract2_2 = {23'b0, Delay2_out1_1};
  assign Subtract2_sub_temp = Subtract2_1 - Subtract2_2;
  assign Subtract2_out1 = Subtract2_sub_temp[9:0];

  assign Constant4_out1_1 = 10'sb0011111111;

  assign Switch2_out1_1 = (Delay3_out1_2 == 1'b0 ? Subtract2_out1 :
              Constant4_out1_1);

  always @(posedge clk or posedge reset)
    begin : Delay27_process
      if (reset == 1'b1) begin
        Delay27_out1 <= 10'sb0000000000;
      end
      else begin
        if (enb) begin
          Delay27_out1 <= Switch2_out1_1;
        end
      end
    end

  assign Constant_out1_1 = 10'sb1100000001;

  assign Switch1_out1_3 = (Compare_To_Zero1_out1_1 == 1'b0 ? Delay27_out1 :
              Constant_out1_1);

  always @(posedge clk or posedge reset)
    begin : Delay5_1_process
      if (reset == 1'b1) begin
        Delay5_out1_1 <= 10'sb0000000000;
      end
      else begin
        if (enb) begin
          Delay5_out1_1 <= Switch1_out1_3;
        end
      end
    end

  assign Bit_Slice25_out1 = Bit_Concat_out1_1[24];

  assign Constant25_out1 = 6'sb011000;

  assign Bit_Slice24_out1 = Bit_Concat_out1_1[25];

  assign Constant24_out1 = 6'sb010111;

  assign Switch24_out1 = (Bit_Slice25_out1 == 1'b0 ? Constant25_out1 :
              Constant24_out1);

  assign Bit_Slice23_out1 = Bit_Concat_out1_1[26];

  assign Constant23_out1 = 6'sb010110;

  assign Switch23_out1 = (Bit_Slice24_out1 == 1'b0 ? Switch24_out1 :
              Constant23_out1);

  assign Bit_Slice22_out1 = Bit_Concat_out1_1[27];

  assign Constant22_out1 = 6'sb010101;

  assign Switch22_out1 = (Bit_Slice23_out1 == 1'b0 ? Switch23_out1 :
              Constant22_out1);

  assign Bit_Slice21_out1 = Bit_Concat_out1_1[28];

  assign Constant21_out1 = 6'sb010100;

  assign Switch21_out1 = (Bit_Slice22_out1 == 1'b0 ? Switch22_out1 :
              Constant21_out1);

  assign Bit_Slice10_out1 = Bit_Concat_out1_1[29];

  assign Constant20_out1 = 6'sb010011;

  assign Switch20_out1 = (Bit_Slice21_out1 == 1'b0 ? Switch21_out1 :
              Constant20_out1);

  assign Bit_Slice19_out1 = Bit_Concat_out1_1[30];

  assign Constant19_out1 = 6'sb010010;

  assign Switch19_out1 = (Bit_Slice10_out1 == 1'b0 ? Switch20_out1 :
              Constant19_out1);

  assign Bit_Slice18_out1 = Bit_Concat_out1_1[31];

  assign Constant18_out1 = 6'sb010001;

  assign Switch18_out1 = (Bit_Slice19_out1 == 1'b0 ? Switch19_out1 :
              Constant18_out1);

  assign Bit_Slice17_out1 = Bit_Concat_out1_1[32];

  assign Constant17_out1 = 6'sb010000;

  assign Switch17_out1 = (Bit_Slice18_out1 == 1'b0 ? Switch18_out1 :
              Constant17_out1);

  assign Bit_Slice16_out1 = Bit_Concat_out1_1[33];

  assign Constant16_out1 = 6'sb001111;

  assign Switch16_out1 = (Bit_Slice17_out1 == 1'b0 ? Switch17_out1 :
              Constant16_out1);

  assign Bit_Slice15_out1 = Bit_Concat_out1_1[34];

  assign Constant15_out1 = 6'sb001110;

  assign Switch15_out1 = (Bit_Slice16_out1 == 1'b0 ? Switch16_out1 :
              Constant15_out1);

  assign Bit_Slice14_out1 = Bit_Concat_out1_1[35];

  assign Constant14_out1 = 6'sb001101;

  assign Switch14_out1 = (Bit_Slice15_out1 == 1'b0 ? Switch15_out1 :
              Constant14_out1);

  assign Bit_Slice13_out1 = Bit_Concat_out1_1[36];

  assign Constant13_out1 = 6'sb001100;

  assign Switch13_out1 = (Bit_Slice14_out1 == 1'b0 ? Switch14_out1 :
              Constant13_out1);

  assign Bit_Slice12_out1 = Bit_Concat_out1_1[37];

  assign Constant12_out1 = 6'sb001011;

  assign Switch12_out1 = (Bit_Slice13_out1 == 1'b0 ? Switch13_out1 :
              Constant12_out1);

  assign Bit_Slice11_out1 = Bit_Concat_out1_1[38];

  assign Constant11_out1 = 6'sb001010;

  assign Switch11_out1 = (Bit_Slice12_out1 == 1'b0 ? Switch12_out1 :
              Constant11_out1);

  assign Bit_Slice_out1 = Bit_Concat_out1_1[39];

  assign Constant10_out1 = 6'sb001001;

  assign Switch10_out1 = (Bit_Slice11_out1 == 1'b0 ? Switch11_out1 :
              Constant10_out1);

  assign Bit_Slice9_out1 = Bit_Concat_out1_1[40];

  assign Constant9_out1 = 6'sb001000;

  assign Switch9_out1 = (Bit_Slice_out1 == 1'b0 ? Switch10_out1 :
              Constant9_out1);

  assign Bit_Slice8_out1 = Bit_Concat_out1_1[41];

  assign Constant8_out1_1 = 6'sb000111;

  assign Switch8_out1 = (Bit_Slice9_out1 == 1'b0 ? Switch9_out1 :
              Constant8_out1_1);

  assign Bit_Slice7_out1 = Bit_Concat_out1_1[42];

  assign Constant7_out1_1 = 6'sb000110;

  assign Switch7_out1 = (Bit_Slice8_out1 == 1'b0 ? Switch8_out1 :
              Constant7_out1_1);

  assign Bit_Slice6_out1 = Bit_Concat_out1_1[43];

  assign Constant6_out1_1 = 6'sb000101;

  assign Switch6_out1 = (Bit_Slice7_out1 == 1'b0 ? Switch7_out1 :
              Constant6_out1_1);

  assign Bit_Slice5_out1 = Bit_Concat_out1_1[44];

  assign Constant5_out1_1 = 6'sb000100;

  assign Switch5_out1 = (Bit_Slice6_out1 == 1'b0 ? Switch6_out1 :
              Constant5_out1_1);

  assign Bit_Slice4_out1 = Bit_Concat_out1_1[45];

  assign Constant4_out1_2 = 6'sb000011;

  assign Switch4_out1 = (Bit_Slice5_out1 == 1'b0 ? Switch5_out1 :
              Constant4_out1_2);

  assign Bit_Slice3_out1 = Bit_Concat_out1_1[46];

  assign Constant3_out1_2 = 6'sb000010;

  assign Switch3_out1_1 = (Bit_Slice4_out1 == 1'b0 ? Switch4_out1 :
              Constant3_out1_2);

  assign Bit_Slice2_out1 = Bit_Concat_out1_1[47];

  assign Constant2_out1_2 = 6'sb000001;

  assign Switch2_out1_2 = (Bit_Slice3_out1 == 1'b0 ? Switch3_out1_1 :
              Constant2_out1_2);

  assign Bit_Slice1_out1 = Bit_Concat_out1_1[48];

  assign Constant1_out1_3 = 6'sb000000;

  assign Switch1_out1_4 = (Bit_Slice2_out1 == 1'b0 ? Switch2_out1_2 :
              Constant1_out1_3);

  assign Constant26_out1 = 6'sb111111;

  assign Switch_out1_3 = (Bit_Slice1_out1 == 1'b0 ? Switch1_out1_4 :
              Constant26_out1);

  always @(posedge clk or posedge reset)
    begin : Delay1_1_process
      if (reset == 1'b1) begin
        Delay1_out1_1 <= 6'sb000000;
      end
      else begin
        if (enb) begin
          Delay1_out1_1 <= Switch_out1_3;
        end
      end
    end

  assign Add_3 = {{22{Delay5_out1_1[9]}}, Delay5_out1_1};
  assign Add_4 = {{26{Delay1_out1_1[5]}}, Delay1_out1_1};
  assign Add_sub_temp = Add_3 - Add_4;
  assign Add_out1_1 = Add_sub_temp[9:0];

  assign Compare_To_Constant_out1_1 = Add_out1_1 <= 10'sb1110000001;

  assign Constant1_out1_4 = 9'sb110000001;

  assign Constant1_out1_dtc = {Constant1_out1_4[8], Constant1_out1_4};

  assign Switch_out1_4 = (Compare_To_Constant_out1_1 == 1'b0 ? Add_out1_1 :
              Constant1_out1_dtc);

  always @(posedge clk or posedge reset)
    begin : Delay18_process
      if (reset == 1'b1) begin
        Delay18_out1 <= 10'sb0000000000;
      end
      else begin
        if (enb) begin
          Delay18_out1 <= Switch_out1_4;
        end
      end
    end

  assign Compare_To_Constant1_out1_1 = Delay18_out1 > 10'sb0001111111;

  assign Logical_Operator1_out1_2 =  ~ Delay14_out1;

  assign Logical_Operator4_out1 = Logical_Operator1_out1_2 & Delay20_out1;

  assign Logical_Operator7_out1 = Logical_Operator4_out1 & Delay21_out1;

  assign Logical_Operator5_out1 =  ~ Delay19_out1;

  assign Logical_Operator6_out1 = Logical_Operator5_out1 & Delay23_out1;

  assign Logical_Operator8_out1 = Logical_Operator6_out1 & Delay16_out1;

  assign Inf_Zero_out1 = Logical_Operator7_out1 | Logical_Operator8_out1;

  assign Logical_Operator2_out1_1 = Logical_Operator_out1 | Logical_Operator1_out1;

  assign Logical_Operator10_out1 = Inf_Zero_out1 | Logical_Operator2_out1_1;

  always @(posedge clk or posedge reset)
    begin : Delay22_process
      if (reset == 1'b1) begin
        Delay22_reg <= {3{1'b0}};
      end
      else begin
        if (enb) begin
          Delay22_reg[0] <= Logical_Operator10_out1;
          Delay22_reg[32'sd2:32'sd1] <= Delay22_reg[32'sd1:32'sd0];
        end
      end
    end

  assign Delay22_out1 = Delay22_reg[2];

  always @(posedge clk or posedge reset)
    begin : Delay13_process
      if (reset == 1'b1) begin
        Delay13_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay13_out1 <= Delay22_out1;
        end
      end
    end

  assign Logical_Operator_out1_4 = Compare_To_Constant1_out1_1 | Delay13_out1;

  assign Compare_To_Constant_out1_2 = Delay18_out1 < 10'sb1110000001;

  assign Constant1_out1_5 = 8'b01111111;

  always @(posedge clk or posedge reset)
    begin : Delay2_2_process
      if (reset == 1'b1) begin
        Delay2_out1_2 <= 49'h0000000000000;
      end
      else begin
        if (enb) begin
          Delay2_out1_2 <= Bit_Concat_out1_1;
        end
      end
    end

  assign Compare_To_Zero_out1_1 = Delay1_out1_1 < 6'sb000000;

  assign Bit_Slice_out1_1 = Delay1_out1_1[4:0];

  assign dynamic_shift_1 = {3'b0, Bit_Slice_out1_1};
  assign Shift_Arithmetic_out1 = Delay2_out1_2 <<< dynamic_shift_1;

  assign Bit_Shift_out1 = Bit_Concat_out1_1 >>> 8'd1;

  always @(posedge clk or posedge reset)
    begin : Delay3_3_process
      if (reset == 1'b1) begin
        Delay3_out1_3 <= 49'h0000000000000;
      end
      else begin
        if (enb) begin
          Delay3_out1_3 <= Bit_Shift_out1;
        end
      end
    end

  assign Switch_out1_5 = (Compare_To_Zero_out1_1 == 1'b0 ? Shift_Arithmetic_out1 :
              Delay3_out1_3);

  // handling denormalized signals
  assign Constant_out1_2 = 9'sb110000010;

  assign Subtract_4 = {{22{Add_out1_1[9]}}, Add_out1_1};
  assign Subtract_5 = {{23{Constant_out1_2[8]}}, Constant_out1_2};
  assign Subtract_sub_temp = Subtract_4 - Subtract_5;
  assign Subtract_out1_1 = Subtract_sub_temp[15:0];

  assign Compare_To_Constant_out1_3 = Subtract_out1_1 < 16'sb1111111111100001;

  assign Subtract_out1_dtc = Subtract_out1_1[5:0];

  assign Compare_To_Constant1_out1_2 = Subtract_out1_1 > 16'sb0000000000011111;

  assign Constant1_out1_6 = 6'sb100001;

  assign Switch_out1_6 = (Compare_To_Constant_out1_3 == 1'b0 ? Subtract_out1_dtc :
              Constant1_out1_6);

  assign Constant2_out1_3 = 6'sb011111;

  assign Switch1_out1_5 = (Compare_To_Constant1_out1_2 == 1'b0 ? Switch_out1_6 :
              Constant2_out1_3);

  assign Unary_Minus_1 = {Switch1_out1_5[5], Switch1_out1_5};
  assign Unary_Minus_in0 =  - (Unary_Minus_1);
  assign Unary_Minus_out1 = Unary_Minus_in0[5:0];

  assign shift_arithmetic_shift_direction = Unary_Minus_out1 < 6'sb000000;

  assign Constant_out1_3 = 31'b0000000000000000000000000000000;

  assign Bit_Concat_out1_3 = {Switch_out1_5, Constant_out1_3};

  assign shift_arithmetic_abs_1 = {Unary_Minus_out1[5], Unary_Minus_out1};
  assign shift_arithmetic_abs_y = (Unary_Minus_out1 < 6'sb000000 ?  - (shift_arithmetic_abs_1) :
              {Unary_Minus_out1[5], Unary_Minus_out1});
  assign shift_arithmetic_shift_value = shift_arithmetic_abs_y;

  assign shift_right_1 = {1'b0, shift_arithmetic_shift_value};
  assign shift_arithmetic_right = Bit_Concat_out1_3 >>> shift_right_1;

  assign shift_left_1 = {1'b0, shift_arithmetic_shift_value};
  assign shift_arithmetic_left = Bit_Concat_out1_3 <<< shift_left_1;

  assign Shift_Arithmetic_out1_1 = (shift_arithmetic_shift_direction == 1'b0 ? shift_arithmetic_right :
              shift_arithmetic_left);

  assign Bit_Slice1_out1_1 = Shift_Arithmetic_out1_1[30:0];

  assign switch_compare_1 = Bit_Slice1_out1_1 != 49'h0000000000000;

  assign Bit_Slice_out1_2 = Shift_Arithmetic_out1_1[79:31];

  assign Bit_Set_out1 = Bit_Slice_out1_2 | 49'h0000000000001;

  assign Switch2_out1_3 = (switch_compare_1 == 1'b0 ? Bit_Slice_out1_2 :
              Bit_Set_out1);

  assign Switch1_out1_6 = (Compare_To_Constant_out1_1 == 1'b0 ? Switch_out1_5 :
              Switch2_out1_3);

  assign Bit_Slice_out1_3 = Switch1_out1_6[47:0];

  assign Bit_Slice2_out1_1 = Bit_Slice_out1_3[23:22];

  assign Bit_Slice4_out1_1 = Bit_Slice2_out1_1[0];

  assign Bit_Slice1_out1_2 = Bit_Slice_out1_3[21:0];

  assign Bit_Reduce_out1 = (|Bit_Slice1_out1_2[21:0]);

  assign Bit_Slice5_out1_1 = Bit_Slice2_out1_1[1];

  assign Bit_Slice3_out1_1 = Bit_Slice_out1_3[24];

  assign Logical_Operator1_out1_3 = Bit_Slice3_out1_1 | (Bit_Slice4_out1_1 | Bit_Reduce_out1);

  assign Logical_Operator_out1_5 = Bit_Slice5_out1_1 & Logical_Operator1_out1_3;

  always @(posedge clk or posedge reset)
    begin : Delay1_2_process
      if (reset == 1'b1) begin
        Delay1_out1_2 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay1_out1_2 <= Logical_Operator_out1_5;
        end
      end
    end

  assign Bit_Slice1_out1_3 = Bit_Slice_out1_3[46:24];

  always @(posedge clk or posedge reset)
    begin : reduced_process
      if (reset == 1'b1) begin
        Bit_Slice1_out1_4 <= 23'b00000000000000000000000;
      end
      else begin
        if (enb) begin
          Bit_Slice1_out1_4 <= Bit_Slice1_out1_3;
        end
      end
    end

  assign Bit_Slice1_out1_dtc = {1'b0, Bit_Slice1_out1_4};

  assign Constant_out1_4 = 1'b1;

  assign Add_6 = {9'b0, Bit_Slice1_out1_4};
  assign Add_7 = {31'b0, Constant_out1_4};
  assign Add_add_temp = Add_6 + Add_7;
  assign Add_out1_2 = Add_add_temp[23:0];

  assign Switch_out1_7 = (Delay1_out1_2 == 1'b0 ? Bit_Slice1_out1_dtc :
              Add_out1_2);

  assign Bit_Slice2_out1_2 = Switch_out1_7[23];

  assign Add1_4 = {24'b0, Constant1_out1_5};
  assign Add1_5 = {31'b0, Bit_Slice2_out1_2};
  assign Add1_add_temp_1 = Add1_4 + Add1_5;
  assign Add1_out1_1 = Add1_add_temp_1[7:0];

  assign Add_9 = {24'b0, Add1_out1_1};
  assign Add_10 = {{22{Delay18_out1[9]}}, Delay18_out1};
  assign Add_add_temp_1 = Add_9 + Add_10;
  assign Add_out1_3 = Add_add_temp_1[7:0];

  assign Constant1_out1_7 = 8'b00000000;

  assign Switch1_out1_7 = (Compare_To_Constant_out1_2 == 1'b0 ? Add_out1_3 :
              Constant1_out1_7);

  assign Constant4_out1_3 = 8'b11111111;

  assign Switch4_out1_1 = (Logical_Operator_out1_4 == 1'b0 ? Switch1_out1_7 :
              Constant4_out1_3);

  assign Switch6_out1_1 = (Relational_Operator_out1 == 1'b0 ? Constant6_out1 :
              Switch4_out1_1);

  always @(posedge clk or posedge reset)
    begin : Delay1_3_process
      if (reset == 1'b1) begin
        Delay1_out1_3 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          Delay1_out1_3 <= Switch6_out1_1;
        end
      end
    end

  assign Bit_Slice4_out1_2 = Switch_out1_7[22:0];

  assign Bit_Shift_out1_1 = Bit_Slice4_out1_2 >> 8'd1;

  assign Switch1_out1_8 = (Bit_Slice2_out1_2 == 1'b0 ? Bit_Slice4_out1_2 :
              Bit_Shift_out1_1);

  assign Constant2_out1_4 = 23'b00000000000000000000000;

  assign Switch2_out1_4 = (Compare_To_Constant_out1_2 == 1'b0 ? Switch1_out1_8 :
              Constant2_out1_4);

  assign Constant5_out1_2 = 23'b00000000000000000000000;

  assign Bit_Set_out1_1 = Switch2_out1_4 | 23'b10000000000000000000000;

  assign Switch7_out1_1 = (Delay13_out1 == 1'b0 ? Constant5_out1_2 :
              Bit_Set_out1_1);

  assign Switch5_out1_1 = (Logical_Operator_out1_4 == 1'b0 ? Switch2_out1_4 :
              Switch7_out1_1);

  always @(posedge clk or posedge reset)
    begin : Delay2_3_process
      if (reset == 1'b1) begin
        Delay2_out1_3 <= 23'b00000000000000000000000;
      end
      else begin
        if (enb) begin
          Delay2_out1_3 <= Switch5_out1_1;
        end
      end
    end

  // Combine FP sign, exponent, mantissa into 32 bit word
  assign nfp_out_pack = {Delay_out1, Delay1_out1_3, Delay2_out1_3};

  assign nfp_out = nfp_out_pack;

endmodule  // nfp_mul_single

